### ISSUE TITLE
Use PCG random generator

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#101]
http://www.pcg-random.org/

**Comment by HowardHinnant** [comment]
One nit to keep in mind on this:  The license appears to have the "binary clause".  The copyright must accompany _compiled_ forms of this software.

**Comment by vinniefalco** [comment]
I wouldn't use that software anyway, its over-engineered with all the template parameters and such. I would just write my own function that does multiplication and bit shifts, and coincidentally it would have use the same constants as PCG.

**Comment by vinniefalco** [comment]
Says Apache license, where are you seeing the binary clause?

**Comment by HowardHinnant** [comment]
https://www.apache.org/licenses/LICENSE-2.0
Search for "Object form".

**Comment by HowardHinnant** [comment]
It is possible that if this is an issue, the author might agree to an exemption on the binary clause.  This is what I did for libc++ as documented here: http://llvm.org/docs/DeveloperPolicy.html#license (search for libc++).  The binary clause was not important to me for libc++ (or any other open source software I have written).  I have no idea whether or not that is true for the pcg author.

**Comment by vinniefalco** [comment]
Not needed
