### ISSUE TITLE
Add SSL WebSocket Client Sample

### ISSUE THREAD

**Issue by jmin911** [vinniefalco/Beast#102]
Please add sample code that illustrates how to use the SSL WebSocket client to connect and send/receive messages.

**Comment by vinniefalco** [comment]
I'll see what I can do!

**Comment by StefanoBelli** [comment]
I'd like it too! Thanks for your work man!

**Comment by vinniefalco** [comment]
Branch **b15** has SSL examples for HTTP and WebSocket:
https://github.com/vinniefalco/Beast/blob/b15/examples/ssl/

**1.0.0-b15** will be published soon.

**Comment by jmin911** [comment]
Thanks!  It definitely helps to get started quickly.

**Comment by vinniefalco** [comment]
Merged to b15
