### ISSUE TITLE
Content-Length: 0

### ISSUE THREAD

**Issue by e-fominov** [vinniefalco/Beast#103]
If I use `response_v1<string_body>` and if string is empty or if `response_v1<empty_body>` - "Content-Length: 0" header will be automatically sent. It looks incorrect for me

[Here](https://github.com/vinniefalco/Beast/blob/master/include/beast/http/impl/message_v1.ipp#L140) I see:
```
    if(pi.connection_value != connection::upgrade)
    {
        if(pi.content_length)
        {
            // VFALCO TODO Use a static string here
            msg.headers.insert("Content-Length",
                std::to_string(*pi.content_length));
        }
        else if(msg.version >= 11)
        {
            msg.headers.insert("Transfer-Encoding", "chunked");
        }
    }
```
But pi.content_length is `boost::optional<std::uint64_t> content_length;`, so I suggest this change:

`if(pi.content_length.is_initialized() && *pi.content_length != 0)`

as all `body_type::writer` classes are returning `uint64_t` for `content_length()` method and not `boost<optional>` - this will lead to `pi.conent_length`  always be initialized but sometimes with zero

This will affect automatic keep-alive in [line 166](https://github.com/vinniefalco/Beast/blob/master/include/beast/http/impl/message_v1.ipp#L166)

**Comment by vinniefalco** [comment]
This code is working as designed, if there is no body we want Content-Length: 0. Or no? Let me double check the RFC...

**Comment by vinniefalco** [comment]
rfc7230 Section 3.3.2:
   A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body.  For example, a Content-Length header
   field is normally sent in a POST request even when the value is 0
   (indicating an empty payload body).  A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.

Your proposed change would leave out Content-Length: 0 on a POST. I guess if the verb is GET and content length is zero then we should leave it out. Is there a list of verbs and whether or not they anticipate a message body?

**Comment by 2underscores-vic** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by vinniefalco** [comment]
How does this look:
```
    if(pi.connection_value != connection::upgrade)
    {
        if(pi.content_length)
        {
            if(*pi.content_length > 0 ||
                ci_equal(msg.method, "POST"))
            {
                // VFALCO TODO Use a static string here
                msg.headers.insert("Content-Length",
                    std::to_string(*pi.content_length));
            }
        }
        else if(msg.version >= 11)
        {
            msg.headers.insert("Transfer-Encoding", "chunked");
        }
    }
```

**Comment by vinniefalco** [comment]
How about this:
```
    if(pi.connection_value != connection::upgrade)
    {
        if(pi.content_length)
        {
            struct set_field
            {
                void
                operator()(request_v1<Body, Headers>& msg,
                    detail::prepare_info const& pi) const
                {
                    using beast::detail::ci_equal;
                    if(*pi.content_length > 0 ||
                        ci_equal(msg.method, "POST"))
                    {
                        msg.headers.insert("Content-Length",
                            std::to_string(*pi.content_length));
                    }
                }

                void
                operator()(response_v1<Body, Headers>& msg,
                    detail::prepare_info const& pi) const
                {
                    msg.headers.insert("Content-Length",
                        std::to_string(*pi.content_length));
                }
            };
            set_field{}(msg, pi);
        }
        else if(msg.version >= 11)
        {
            msg.headers.insert("Transfer-Encoding", "chunked");
        }
    }
```

**Comment by vinniefalco** [comment]
You can try it out here:
https://github.com/vinniefalco/Beast/commits/b15

**Comment by e-fominov** [comment]
Is it possible that [this line](https://github.com/vinniefalco/Beast/blob/5ecf8de7d3d20a783dcc88ec577f1d88539e4cd0/include/beast/http/impl/message_v1.ipp#L141) condition will be false? `if (pi.content_length)`

And every server response will have "Content-Length: 0" header.  [RFC 7320](https://tools.ietf.org/html/rfc7230#section-3.3.2) defines several situations when server MUST NOT send this header, for example:

> A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request (Section 4.3.6 of
   [RFC7231]).

On server side, if I use `response_v1<empty_body>` - i will have this header in response for any status code . May be empty_body should not have `empty_body::content_length` member, as it returns 0 and `if (pi.content_length)` becomes true.

**Comment by vinniefalco** [comment]
Thank you. That's the information that I need - we need to go through the entire RFC and make sure that all the requirements are respected.

**Comment by vinniefalco** [comment]
Okay, I made the changes, this is the modified code:
```
                void
                operator()(message_v1<false, Body, Headers>& msg,
                    detail::prepare_info const& pi) const
                {
                    if((msg.status / 100 ) != 1 &&
                        msg.status != 204)
                    {
                        msg.headers.insert("Content-Length",
                            std::to_string(*pi.content_length));
                    }
                }
```

I rewrote the branch in this pull request:
https://github.com/vinniefalco/Beast/commits/b15

**Comment by e-fominov** [comment]
Ok, this will make messages more standard-compiant. There are still many situations that are not covered by this solution. 
Looks like `prepare` function becomes more and more complicated and it makes high-level protocol handling, that should be made somewhere else. 
Do you have plans for making high-level protocol algorithms?

**Comment by vinniefalco** [comment]
I don't have any plans to add high-level protocol algorithms to Beast. The intent of this library is to offer only the low level HTTP functionality. I hope that other people (maybe you?) will build on Beast to provide high level functions.

That said, there is no requirement that you call `prepare`. You can just skip the call and set fields manually.

**Comment by 2underscores-vic** [comment]
What about status 304 (Not Modified)?

**Comment by vinniefalco** [comment]
@2underscores-vic Yep, I missed that one, sorry about it! I have updated the b15 branch (force-pushed). Thanks!
