### ISSUE TITLE
best way to implement blocking-with-timeout read

### ISSUE THREAD

**Issue by TojNALvViV** [vinniefalco/Beast#116]
Hi Vinnie,

I am wondering - what is the best way to implement a blocking websocket read (say) that returns either after something is received or a given timeout period elapses? Is this something that should go into Beast, or something that should be written on top of it?

**Comment by vinniefalco** [comment]
For asynchronous operations, there are many ways to implement a timer - each with its own advantages and disadvantages. For this reason, it makes more sense to push the responsibility for providing timeout facilities on to users of Beast. Asio makes a similar choice - none of its interfaces allow for timeouts, but you can build a timeout facility yourself.

For synchronous operations, I don't know that its possible to implement a timeout feature. How would it be done? `ip::tcp::socket::cancel` is not thread safe.

**Comment by vinniefalco** [comment]
Is this resolved?

**Comment by vinniefalco** [comment]
Looks like this is no longer an issue. If you feel it is still relevant, please re-open it.
