### ISSUE TITLE
 websocket server crashes

### ISSUE THREAD

**Issue by goflatworld** [vinniefalco/Beast#147]
Thanks for your great help so far. I have added the websocket part to my server (not the one on github, the server is kind a commercial software, not really comfortable to put it on github ). During test, it crashes quite often. When the server crashes, the output is as below:

server: /usr/include/beast/websocket/detail/invokable.hpp:138: void beast::websocket::detail::invokable::emplace(F&&) [with F = beast::websocket::streamboost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp > >::write_frame_op >, beast::websocket::streamboost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp > >::write_op, boost::bi::list2boost::_bi::value<std::shared_ptr<websocket::applications::chat::session >, boost::arg<1> (*)()> >, boost::asio::detail::is_continuation_if_running> > >]: Assertion `! base' failed.

My server has two clients connect to it: one is a websocket client (I call it control), another one is normal socket client (I call it agent).

I uses "control" client to control the "agent" (when I say control, I meant I type some command on the "control", it sends to server, server sends to "agent"). Then "agent" performs the required functions and sends result back.

During test, if I send same command from "control" to "agent", it works sometimes but crashes another time.

I also have a normal socket client to control the "agent". It worked fine. I want to replace the normal client with websocket client.

Can you please give me some hints on where should I look into it?

If code is required, can I send to you via email?

**Comment by vinniefalco** [comment]
Please try this branch **invokable** and see if it solves your problem:
https://github.com/vinniefalco/Beast/commits/invokable

**Comment by goflatworld** [comment]
Thanks for the quick response. I have tried the new version. So far, no crashes anymore. Thanks again.

I'll update the case if it crashes again.

**Comment by goflatworld** [comment]
Today, it crashed twice. 

The first time, the error message is as below. The second time I didn't capture the error becuase my ssh session got disconnected. 

============================================

server: /usr/include/beast/websocket/detail/invokable.hpp:138: void beast::websocket::detail::invokable::emplace(F&&) [with F = beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_frame_op<beast::prepared_buffers<beast::consuming_buffers<boost::asio::const_buffers_1, boost::asio::const_buffer> >, beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_op<boost::asio::const_buffers_1, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf1<void, websocket::applications::chat::session, const boost::system::error_code&>, boost::_bi::list2<boost::_bi::value<std::shared_ptr<websocket::applications::chat::session> >, boost::arg<1> (*)()> >, boost::asio::detail::is_continuation_if_running> > >]: Assertion `! base_' failed.

==========================================================

**Comment by vinniefalco** [comment]
The purpose of `invokable` is to "park" a websocket operation. These operations are:
* `write_frame_op`
* `read_frame_op`
* `close_op`

An operation is parked when it needs to read or write, and doing so would conflict with another operation. Consider the case where `read_frame_op` encounters a ping frame. `websocket::stream` automatically handles this case for you, by sending a pong in response. But what if you already have a write pending (such as an active call to `stream::async_write`? In this case, the implementation "parks" the read operation in the invokable. Later, when that pending write completes, it resumes the read operation by executing the invokable. That happens near the end of each operation. For example, near the end of `write_frame_op`:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/write_frame_op.ipp#L266

There is one invokable slot for read, and one slot for write. Your program is crashing because the implementation tried to park an operation into an invokable which is already occupied, which breaks an invariant. `websocket::stream` allows only one pending asynchronous read and one pending asynchronous write.

These functions count as reads:
* `websocket::stream::async_read`
* `websocket::stream::async_read_frame`

These functions count as writes:
* `websocket::stream::async_write`
* `websocket::stream::async_write_frame`
* `websocket::stream::async_ping`
* `websocket::stream::async_close`

One obvious way that comes to mind for this to happen, is if you are trying to execute two write operations at the same time. `async_close` counts as a write. Are you calling `async_write` and `async_close` before either of them complete? That would cause the assertion.

Please study your code and make sure that you are not issuing multiple calls to functions that read or write, without waiting for one of them to complete. Also, please verify that all calls to `websocket::stream` functions are protected by an implicit or explicit strand. The easiest way to do that is to allow only one thread to call `io_service::run`. And, please verify that you are not calling asynchronous `websocket::stream` functions concurrently. Doing any of these previously mentioned things will break invariants and can cause the assertion you are experiencing.

If you are certain that you are not breaking any of the stream invariants, the next step unfortunately is that you will have to help diagnose the problem. The best thing you can provide is a small test program that duplicates the defect. Other than that, any additional information you can find out from debugging would be helpful. I can also take a look at your source code if you create a private repository and add me as a collaborator (add my GitHub id *vinniefalco*). Any access you provide will be considered confidential.

It would be nice to know which call to `invokable::emplace` is generating the assertion failure. These are all the places where it is called:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/close_op.ipp#L140
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/ping_op.ipp#L139
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L330
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L370
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L486
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/write_frame_op.ipp#L181

If you can instrument the program to add some additional logging or parameters to emplace so that we know which line caused the failure, it can help us diagnose the problem.

**Comment by goflatworld** [comment]
I'll review the code and continue test it. That might take some days. Thanks for the detailed explanation of how it works.

**Comment by goflatworld** [comment]
I got the feeling that this might be caused by bad network connection although I can not confirm this yet. The reason I get the feeling is that when my network is good, the application doesn't crash. When my network is bad (when I say bad, I tried to open any web page, it times out). The server crash quite often. 

I'll keep test it for few more days to see whether this feeling is correct or not.

**Comment by vinniefalco** [comment]
Still, bad network conditions should not cause an application failure. Probably you are not handling errors correctly (the `error_code&` params on completion handlers). Shutting down sockets cleanly is always difficult in async programs.

**Comment by goflatworld** [comment]
Thanks for the tips, I'll check the socket shutdown.

**Comment by goflatworld** [comment]
I have uploaded my project to github in private mode and have added you to view the code.

https://github.com/goflatworld/Stingray

Can you please review the code and see what I'm doing wrong in there?

The server still crash quite often sometimes.

Thanks

George

**Comment by goflatworld** [comment]
Can you please let me know whether you can access the code or not?

**Comment by vinniefalco** [comment]
Yes, I can see the code. But its a big program and nothing immediately jumps out at me.

**Comment by goflatworld** [comment]
Thanks for looking into it.

The key code is in the session.cpp. In this file, I have two parts, one handles normal socket. One handles HTTP socket. The crash is in the HTTP socket part.

**Comment by vinniefalco** [comment]
You're missing a strand here:
https://github.com/goflatworld/Stingray/blob/master/session.cpp#L336

**Comment by goflatworld** [comment]
Thanks for pointing this out. I have checked the code and tested. It crashes with same error messages. During my test, I'm fairly sure there are only two socket connect to the server, one is the normal socket client and another one is websocket client. I shouldn't have any close operation during the crash.

My application is a telnet like application, the normal socket client sends only 6 chars  to the server in one async_write. The server decoded the packet and send ONE char to the websocket in one async_write. So my write operation happens quite a lot (e.g. several hundreds a second). Can this cause any issue?

**Comment by vinniefalco** [comment]
There should be no problem sending many messages

**Comment by goflatworld** [comment]
Thanks. Do you mind looking into the modified code to see if you can find out any issue?

**Comment by vinniefalco** [comment]
I looked at it again, but nothing jumps out. It looks like if flag==0 then its a normal websocket connection but if flag==1 then its something else? Do you ever try to mix the two on the same connection?

**Comment by goflatworld** [comment]
If flag==0 it is a websocket, if flag==1, it is a normal socket. 

In my testing, I only had two connections, one was websocket, one was normal socket. I type command on the websocket client, sends to server, server sends to normal socket client. Normal socket client return result to server, server send to websocket. The crash happens when the packets are from server to websocket client.

I have modified the code to give flag a -1 value just in case flag might have a default value of 0 or 1.

**Comment by vinniefalco** [comment]
You're going to have to debug it. What's the crash? Is there a stack?

**Comment by goflatworld** [comment]
The process stops with below errors printed on the screen, that's all I have at this stage:

erver: /usr/include/beast/websocket/detail/invokable.hpp:138: void beast::websocket::detail::invokable::emplace(F&&) [with F = beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_frame_op<beast::prepared_buffers<beast::consuming_buffers<boost::asio::const_buffers_1, boost::asio::const_buffer> >, beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_op<boost::asio::const_buffers_1, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf1<void, websocket::applications::chat::session, const boost::system::error_code&>, boost::_bi::list2<boost::_bi::value<std::shared_ptr<websocket::applications::chat::session> >, boost::arg<1> (*)()> >, boost::asio::detail::is_continuation_if_running> > >]: Assertion `! base_' failed.

**Comment by vinniefalco** [comment]
Oh, right - that. I already gave you some instructions, did you have the chance to follow them? I will repeat it here:

>If you are certain that you are not breaking any of the stream invariants, the next step unfortunately is that you will have to help diagnose the problem. The best thing you can provide is a small test program that duplicates the defect. Other than that, any additional information you can find out from debugging would be helpful. I can also take a look at your source code if you create a private repository and add me as a collaborator (add my GitHub id vinniefalco). Any access you provide will be considered confidential.

>It would be nice to know which call to invokable::emplace is generating the assertion failure. These are all the places where it is called:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/close_op.ipp#L140
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/ping_op.ipp#L139
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L330
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L370
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/read_frame_op.ipp#L486
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/write_frame_op.ipp#L181

>If you can instrument the program to add some additional logging or parameters to emplace so that we know which line caused the failure, it can help us diagnose the problem.

**Comment by goflatworld** [comment]
Thanks. I'll try to think about how to debug it.

**Comment by vinniefalco** [comment]
You can edit invokable.hpp and make copies of the `emplace` function, name them `emplace1`, `emplace2`, etc..  and then from each place where `emplace` is called, call one of the new functions (uniquely). Then edit the BOOST_ASSERT in the body of each `emplace` function to put some descriptive text for example
```
BOOST_ASSERT((! base_) && "1");
```
or
```
BOOST_ASSERT((! base_) && "2");
```

etc...

**Comment by goflatworld** [comment]
Thanks for the hint, here is my understanding on how to do it:

1. Modify the .hpp file as below:

.........................................................................

template<class F>
void
invokable::emplace_1(F&& f)
{
    static_assert(sizeof(buf_type) >= sizeof(holder<F>),
        "buffer too small");
    BOOST_ASSERT(! base_, && "1");
    ::new(buf_) holder<F>(std::forward<F>(f));
    base_ = reinterpret_cast<base*>(&buf_[0]);
}

template<class F>
void
invokable::emplace_2(F&& f)
{
    static_assert(sizeof(buf_type) >= sizeof(holder<F>),
        "buffer too small");
    BOOST_ASSERT(! base_, && "2");
    ::new(buf_) holder<F>(std::forward<F>(f));
    base_ = reinterpret_cast<base*>(&buf_[0]);
}

.........................................................................


2. In https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/close_op.ipp#L140

I modify emplace to emplace_1

In https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/ping_op.ipp#L139
I modify emplace to emplace_2

3. Repeat step 1 and 2, until i modify "emplace" to emplace_6.

If this is correct, I'll do it now and test it out.

**Comment by vinniefalco** [comment]
Yes! Don't forget about the ones in `read_frame_op.ipp`

**Comment by goflatworld** [comment]
Done and tested, it is this line called emplace and crashed. I'll do more test to see if it always ends up here or not. 

https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/write_frame_op.ipp#L181

server: /usr/include/beast/websocket/detail/invokable.hpp:215: void beast::websocket::detail::invokable::emplace_6(F&&) [with F = beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_frame_op<beast::prepared_buffers<beast::consuming_buffers<boost::asio::const_buffers_1, boost::asio::const_buffer> >, beast::websocket::stream<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >::write_op<boost::asio::const_buffers_1, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf1<void, websocket::applications::chat::session, const boost::system::error_code&>, boost::_bi::list2<boost::_bi::value<std::shared_ptr<websocket::applications::chat::session> >, boost::arg<1> (*)()> >, boost::asio::detail::is_continuation_if_running> > >]: Assertion `! base_ && "6"' failed.

**Comment by vinniefalco** [comment]
So, that will happen if you try to call `async_write` a second time without getting a completion for the first call.

**Comment by goflatworld** [comment]
All my async_write is in the session.cpp and they have strand_.wrap. What could it be then?

flatworld@FlatWorld:~/workspace/Stingray/V2/beast$ grep async_write *
grep: lib: Is a directory
Binary file server matches
Binary file serverbak matches
session.cpp:                wssocket_.async_write(
session.cpp:                boost::asio::async_write(wssocket_.next_layer(),
session.cpp:                boost::asio::async_write(wssocket_.next_layer(),
grep: xterm.js: Is a directory

**Comment by vinniefalco** [comment]
I don't know! You're going to have to debug it. Try checking a bool before calling `websocket_.async_write`, set the bool before the call, and clear it in the completion, to make sure you aren't calling it twice in a row.

Try adding some logging, for every time you call async_write. Try getting a breakpoint at the moment of the assert and see what other threads are doing. I can't really help much, you need to debug it and get more information.

**Comment by goflatworld** [comment]
Just let you know that I commented out BOOST_ASSERT just for testing purpose. 

//    BOOST_ASSERT(! base_ && "6");

Now it appears OK... I used to run a command which generates around 640KB data (meaning 640,000 write operations). Before the change, it crashes several times to get it done once. Now, I have finished two commands without any issue.

I'm not sure what happened. I understand it might be too early to say it works and understand it is probably not the way the software should be written. 

I'll test for a few days to see if I have any crashes or not and update here.

**Comment by vinniefalco** [comment]
I believe I see the problem:
https://github.com/goflatworld/Stingray/blob/master/session.cpp#L515

This code (channel.cpp) can call `session::deliver` twice in a row, without waiting for the completion. As I said earlier:

>Please study your code and make sure that you are not issuing multiple calls to functions that read or write, without waiting for one of them to complete. 

If you want to call `deliver` without waiting, then you need a queue of `chat_message` and make sure you only send one at a time.

**Comment by goflatworld** [comment]
Great thanks for this one. I'll think about it on how to modify it. Probably take your idea of a Bool value in the session.cpp for the deliver function. Thanks for your great help and patience. I also think this should be the root cause.

Meanwhile, just let you know, the application is still running OK at the moment, I have finished three commands without any issue. Something for me to learn in the future as well. 

Again, thanks for our great help and patience. I really appreciated your help.

**Comment by vinniefalco** [comment]
Your app will seem to function with the assert turned off, but the moment the client starts sending pings and pongs you will probably crash.

**Comment by goflatworld** [comment]
Thanks for the explanation. It makes total sense now.

**Comment by goflatworld** [comment]
So far, it works like charm! You have written a great library.
