### ISSUE TITLE
WebSocket Benchmarks

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#157]
If someone could use this benchmarking program to test the performance that would be great:
https://github.com/uWebSockets/uWebSockets/tree/master/benchmarks#websocket-echo-server-benchmarks

**Comment by alexhultman** [comment]
Current results can be found here: https://github.com/uWebSockets/uWebSockets#benchmarks-table---validate

**Comment by vinniefalco** [comment]
Thanks for taking the time to run the benchmarks
