### ISSUE TITLE
More async examples please.

### ISSUE THREAD

**Issue by miguelportilla** [vinniefalco/Beast#165]
Please provide more async examples. It would be nice to see how an asynchronous websocket server should send a standard string. More Handler examples etc...

**Comment by xhh** [comment]
Any examples on how to achieve `server.set_message_handler(&on_message)` like in WebSocket++?

**Comment by GregoryEAllen** [comment]
I'll second this one. I'd like to see an async websocket server example.

**Comment by vinniefalco** [comment]
You mean like this one?
https://github.com/vinniefalco/Beast/blob/master/test/websocket/websocket_async_echo_server.hpp

**Comment by vinniefalco** [comment]
>Any examples on how to achieve server.set_message_handler(&on_message) like in WebSocket++

No, because Beast is not designed like websocketpp. It follows the Boost.Asio pattern of one completion handler per asynchronous operation. If you want to read messages, use `read` or `async_read`:
http://vinniefalco.github.io/beast/beast/ref/websocket__stream/async_read.html

**Comment by vinniefalco** [comment]
I should make a copy of the echo servers without the extra code for the unit tests and put it examples/

**Comment by GregoryEAllen** [comment]
@vinniefalco I did find the one in test, but had a hard time telling how much was test and how much was example. Is there a compelling reason for wrapping all the members in `Peer::data`?

**Comment by vinniefalco** [comment]
> Is there a compelling reason for wrapping all the members in `Peer::data`?

Yes, this is the style of code I use when I write asynchronous _composed operations_.
http://blog.think-async.com/2009/08/composed-operations-coroutines-and-code.html
