### ISSUE TITLE
HEAD requests

### ISSUE THREAD

**Issue by dirkvdb** [vinniefalco/Beast#172]
I'm trying to do a HEAD request using beast.
Reading the response gives an error: unexpected end of data

Response data:
HTTP/1.1 200 OK\r\n
SERVER: Darwin/15.4.0, UPnP/1.0\r\n
CONTENT-LENGTH: 15\r\n
CONTENT-TYPE: plain/text\r\n
\r\n

It seems wrong to give an error when responding to a HEAD request, since no data should be in the response.

**Comment by vinniefalco** [comment]
Beast uses free functions to send and receive HTTP messages, so it doesn't "know" that the request you sent was a HEAD request. When it receives the response, it sees "Content-Length: 15" and assumes that it is going to see a body. You can use `beast::http::parse` with an instance of `beast::http::parser_v1` with the `skip_body` option set to `true`. Sample code to do so would look like this:
```
using namespace beast::http;
streambuf sb;
parser_v1<true, empty_body, headers> p;
p.set_option(skip_body{true});
read(socket, sb, p);
```

I will add additional overloads of `read` and `async_read` to make it easier to read into a `message_headers` object, see #173

**Comment by vinniefalco** [comment]
In **1.0.0-b19** there will be another choice (from #173):
```
using namespace beast::http;
streambuf sb;
response_headers res;
read(socket, sb, res); // read a response to HEAD request
```

Is this suitable?

**Comment by dirkvdb** [comment]
Yes, that loods good. I will try out the commit tomorrow. (Past midnight here :-)

Thanks for the fast response!

**Comment by vinniefalco** [comment]
This branch has the changes for `read` to work with `message_headers`
https://github.com/vinniefalco/Beast/tree/headers

**Comment by dirkvdb** [comment]
It works fine, thanks!
