### ISSUE TITLE
http::with_body incorrectly receives the headers_parser by reference instead of && 

### ISSUE THREAD

**Issue by georgi-d** [vinniefalco/Beast#177]
The implementation of http::with_body conflicts with its documentation because it takes the header_parser by reference instead of &&. 

The example:

`auto p = with_body<string_body>(std::move(ph));`

cannot work because the result of std::move cannot bind to a non-const reference.

The implementation of with_body does the move itself at the moment but I think it would be better for the move to be as in the example when calling with_body

**Comment by vinniefalco** [comment]
I see, so you're saying it should look like this:
```
template<class Body, bool isRequest, class Headers, class... Args>
parser_v1<isRequest, Body, Headers>
with_body(headers_parser_v1<isRequest, Headers>&& parser,
    Args&&... args)
{
    return parser_v1<isRequest, Body, Headers>(
        std::move(parser), std::forward<Args>(args)...);
}

template<class Body, bool isRequest, class Headers, class... Args>
parser_v1<isRequest, Body, Headers>
with_body(headers_parser_v1<isRequest, Headers> const& parser,
    Args&&... args)
{
    return parser_v1<isRequest, Body, Headers>(
        parser, std::forward<Args>(args)...);
}
```

**Comment by vinniefalco** [comment]
Proposed fix
https://github.com/vinniefalco/Beast/commit/8040107f60bd3eb1c5cd0fb3c7a63bd62a29508d

**Comment by vinniefalco** [comment]
Sorry, no, that's not how its supposed to work. The example code is wrong. It should read:
```
auto p = with_body<string_body>(ph);
```

It is not necessary to move the headers parser.

**Comment by vinniefalco** [comment]
I believe this is the correct fix: https://github.com/vinniefalco/Beast/commit/b968887b642f6b53b276648068d4efa88d895ae2

**Comment by georgi-d** [comment]
I thought the comment should stay as is and the implementation change to:
```

template<class Body, bool isRequest, class Headers, class... Args>
parser_v1<isRequest, Body, Headers>
with_body(headers_parser_v1<isRequest, Headers>&& parser,
    Args&&... args)
{
    return parser_v1<isRequest, Body, Headers>(
        std::forward(parser), std::forward<Args>(args)...);
}
```

The implicit move inside with_body() feels surprising to me, I feel it would be better to be explicit at the call site of with_body.

Do you have a use case where the headers parser would not be moved in the end?

**Comment by vinniefalco** [comment]
>Do you have a use case where the headers parser would not be moved in the end?

The `headers_parser` is never moved. Only the `message` inside is moved, as if by `parser.release()`

The parser is a stateless POD type object, there's nothing to move except for the message.

**Comment by georgi-d** [comment]
The current implementation  moves the parser:

return parser_v1<isRequest, Body, Headers>( **std::move(parser)**, std::forward<Args>(args)...);

If the move is not needed then the code should be:
```

template<class Body, bool isRequest, class Headers, class... Args>
parser_v1<isRequest, Body, Headers>
with_body(headers_parser_v1<isRequest, Headers>& parser,
    Args&&... args)
{
    return parser_v1<isRequest, Body, Headers>(
        parser, std::forward<Args>(args)...);
}
```

**Comment by vinniefalco** [comment]
@georgi-d Let me tell you, this little problem turned out to be a huge pain. This is the latest version of the fix: https://github.com/vinniefalco/Beast/commit/b5432f8e0da8ee841b2da34bb418ef61ed0aace3

**Comment by georgi-d** [comment]
This version looks good to me.

Thanks
