### ISSUE TITLE
Extending beast::http::request

### ISSUE THREAD

**Issue by avalchev** [vinniefalco/Beast#183]
I need additional information to be added to request, such as cookies or request timestamp.

Is extending `beast::http::request` class is a good practice or composition must be used ?

For example:
```
class Request: public beast::http::request<beast::http::streambuf_body>
{
public:

  Request() {}

  virtual ~Request() {}

private:

  std::map<std::string, std::string> _cookies;

};
```

Thanks :)

**Comment by vinniefalco** [comment]
If you're asking whether you should derive from `beast::http::message`, or have `beast::http::message` as a data member in your class, I would suggest the data member (i.e. composition).

**Comment by avalchev** [comment]
Thanks :)
