### ISSUE TITLE
Configurable maximum header size.

### ISSUE THREAD

**Issue by avalchev** [vinniefalco/Beast#194]
I'm currently sending HTTP requests to Beast server with header value of 20000 bytes. It behaves really well by rejecting client request (closing connection).

However, is it possible to configure maximum header size ?

As far as I remember Joyent http parser, doesn't have such option and maximum size is fixed to 8086 (or something...).

**Comment by vinniefalco** [comment]
Yes, see:
http://vinniefalco.github.io/beast/beast/ref/http__header_max_size.html

**Comment by avalchev** [comment]
Cool, thanks.

**Comment by avalchev** [comment]
Something is not clear for me. 

I'm reading response with:

```
beast::http::async_read(_socket, request, action);
```

How to set this option ?

**Comment by vinniefalco** [comment]
>

**Comment by vinniefalco** [comment]
>In order to make use of this option, you have to call async_parse instead of async_read. And you need to set the options on the parser, and manage the parser's lifetime.

Something like this:
```
template<class AsyncReadStream>
void do_read(AsyncReadStream& stream, yield_context yield)
{
    parser_v1<true, string_body, fields> p;
    p.set_option(header_max_size{32768});
    streambuf sb;
    async_parse(stream, p, sb, yield);
    message<true, string_body, fields> msg = p.release();
}
```

**Comment by avalchev** [comment]
Great example !

I'll close the issue and reopen if need more help :)

Thanks.
