### ISSUE TITLE
Make parse operations independent from boost.asio for use in microcontrollers

### ISSUE THREAD

**Issue by felipealmeida** [vinniefalco/Beast#199]
beast/http/impl/parse.ipp and beast/http/stream_concepts.hpp depend on asio types, which makes it impossible to use the parsing and generation of HTTP/WS messages without #include'ing boost.asio, which can't compile on microcontrollers on bare metal or RTOS.

**Comment by felipealmeida** [comment]
I have some patches. But involves patching asio too, to separate misc_errors from other network related errors.

**Comment by vinniefalco** [comment]
Sounds like its a much bigger job than just minor changes in `basic_parser_v1.hpp`. I would like to address this, but it would have to happen after the Boost formal review when I am less busy.

**Comment by vinniefalco** [comment]
You have to at least have `<boost/asio/buffer.hpp>` can you see if that compiles?

**Comment by vinniefalco** [comment]
@felipealmeida Were you ever able to find out if boost/asio/buffer.hpp compiles for you? If you do, please re-open this issue!
