### ISSUE TITLE
HTTP SSL Server and WebSocket SSL Server Examples

### ISSUE THREAD

**Issue by jmin911** [vinniefalco/Beast#206]
Very good and easy to construct HTTPS and WebSocket SSL client side.
However, I am having difficulty making the HTTPS and WebSocket SSL server side work.  Would be great if there are examples that show HTTPS and WebSocket SSL server code.
SSL is very important as nowadays, everything needs to be communicated in secure channels.
Thanks,

**Comment by rberlich** [comment]
There is a comprehensive echo websocket server example under test/websocket/websocket_async_echo_server.hpp . Any chance this gets promoted to an example rather than a test? Or, more preferably, ist there a chance of a websocket server example accepting std::function<> arguments for the likes of "onopen", "onmessage", "onerror" and "onclose" ? I suppose that this is what most people intending to build a protocol exchance on top of Beast would be looking for.

Thanks and a happy new year to you all,
Beet

**Comment by vinniefalco** [comment]
>Any chance this gets promoted to an example rather than a test

Yeah, that's on my to-do. The reason it is still a test, is because it has some extra code in it to facilitate the unit tests. Code like this:
https://github.com/vinniefalco/Beast/blob/master/test/websocket/websocket_async_echo_server.hpp#L234

**Comment by rberlich** [comment]
Hi Vinnie, o.k., I take it that for everyday usage the "RAW" section of operator() in the above test is irrelevant. Do I understand it correctly that all "payload / message" data is received in /* else if(match(d.db, "TEXT")) */ ? What about binary frames ? Essentially I want to exchange some serialized objects between clients and a server, following a simple, custom protocol. I can of course uuencode everything, but would prefer to be able to "just" send Boost.Serialize-data. Thanks, Beet

**Comment by vinniefalco** [comment]
That is correct, all of that "RAW", "TEXT', etc.. are custom message payloads to facilitate testing. The value `d.op` (or `d_->op`) indicates whether the incoming payload is binary or text. To set the outgoing message type use `stream::set_option`:
http://vinniefalco.github.io/beast/beast/ref/websocket__stream/set_option/overload5.html http://vinniefalco.github.io/beast/beast/ref/websocket__message_type.html

**Comment by rberlich** [comment]
O.k., thanks. Kind Regards, Beet

**Comment by vinniefalco** [comment]
@rberlich The change to make the servers part of the examples will go into **1.0.0-b25**, thanks!

**Comment by vinniefalco** [comment]
There's a websocket ssl server now

**Comment by vinniefalco** [comment]
https://github.com/vinniefalco/Beast/blob/master/test/websocket/ssl/websocket_async_ssl_echo_server.hpp

**Comment by vinhemotiv** [comment]
Hi Vinnie, 
when i build your examples code. I always throw and exception. Look like echo ssl server is not working yet ???
 try
        {
            for(;;)
            {
                ws.read(op, b);
                b.consume(b.size());
            }
        }
        catch(system_error const& se)
        {
            if(se.code() != beast::websocket::error::closed)
                throw;
        }
        BEAST_EXPECT(boost::lexical_cast<std::string>(
            buffers(b.data())) == "Hello, world!");

**Comment by vinniefalco** [comment]
I don't know why that's not working for you. The asynchronous echo servers runs as part of the tests, and it has never thrown an exception on my machine or on the numerous Travis CI matrix configuratons:
https://github.com/vinniefalco/Beast/blob/master/test/websocket/ssl/ssl_server.cpp#L131

**Comment by vinhemotiv** [comment]
I was able to build your all projects, examples, and test with Visual Studito. 
How can i run test ? 
        server.open(endpoint_type{
            address_type::from_string("127.0.0.1"), 6000 }, ec); => open port 6000
And handshake at what port ?        
beast::websocket::stream<stream_type&> ws{stream};
        ws.handshake("localhost", "/");

Thank alot for your help
Vinh

**Comment by vinniefalco** [comment]
Please use the Github flavored markdown to format code (triple backquote blocks).

There are some problems with the code you gave me. Where are you making the connection? What is `stream_type`?

**Comment by vinhemotiv** [comment]
https://github.com/vinniefalco/Beast/blob/master/test/websocket/ssl/ssl_server.cpp

I just built everything from your code. Don't change anything.
![exception](https://cloud.githubusercontent.com/assets/13267003/26782943/fe389fcc-4a1f-11e7-91ce-82172e3a3ca9.PNG)

**Comment by vinniefalco** [comment]
I don't see the value of `se.what()`

**Comment by vinniefalco** [comment]
@jmin911 @vinhemotiv Please consider participating in the Boost formal review for Beast, which starts on July 1st. All you need to do is sign up to the Boost developers mailing list (https://lists.boost.org/mailman/listinfo.cgi/boost) ahead of time and listen for the announcement from the review manager. Your review is vital to the health and success of the library - whether you have positive things to say, or negative things to say, feedback is the only way for Beast to get better!

**Comment by rberlich** [comment]
Dear Vinnie,

I plan to participate, as promised.

Kind Regards,
Ruediger

**Comment by vinhemotiv** [comment]
Dear Vin, I will participate.

**Comment by vinhemotiv** [comment]
Btw, i have another question. How can Beast can handle a Websoket in CLOSE_WAIT status ?
There are some cases that client apps couldn't  close websocket correctly. So i want to handle that case in order to force to close websocket.
Best regards,
Vinh

**Comment by vinniefalco** [comment]
I'm not sure I understand the question. How do you want CLOSE_WAIT to be handled?

**Comment by vinniefalco** [comment]
This is done in server-framework.

@vinhemotiv You can use the code in `example/server-framework` it handles closing connections correctly in all cases.
