### ISSUE TITLE
intellisense doesn't seem to work when the beast header is included.

### ISSUE THREAD

**Issue by taenaism** [vinniefalco/Beast#213]
If I include this header, intellisense seem to stop working.

#include <beast\http.hpp>

I am using Visual Studio 2015 Update 3. I tried it with a new project and just copy and paste the example code in and also added the necessary includes. What could be the problem?

**Comment by vinniefalco** [comment]
No idea. Try using a forward slash?

**Comment by maddinat0r** [comment]
That's an IntelliSense bug. Already reported it [here](https://connect.microsoft.com/VisualStudio/feedback/details/3114172/intellisense-stops-working-after-using-a-specific-template-function), didn't get much reaction though.
If you remove [these lines](https://github.com/vinniefalco/Beast/blob/09c183d1124385ab5dcd9a2e5c4df819bd94807c/include/beast/core/detail/is_call_possible.hpp#L64-L83), IntelliSense should start working again.

**Comment by taenaism** [comment]
Thanks for your reply!

I will give this a try. This is a wonderful library. :)

On 24 Dec 2016, at 6:05 PM, Alex Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


That's an IntelliSense bug. Already reported it here<https://connect.microsoft.com/VisualStudio/feedback/details/3114172/intellisense-stops-working-after-using-a-specific-template-function>, didn't get much reaction though.
If you remove these lines<https://github.com/vinniefalco/Beast/blob/09c183d1124385ab5dcd9a2e5c4df819bd94807c/include/beast/core/detail/is_call_possible.hpp#L64-L83>, IntelliSense should start working again.

-

**Comment by vinniefalco** [comment]
This is great, thanks!!!

**Comment by MerryMage** [comment]
You can [wrap the lines in an `#ifdef __INTELLISENSE__` macro](https://blogs.msdn.microsoft.com/vcblog/2011/03/29/troubleshooting-tips-for-intellisense-slowness/) to disable parsing during an intellisense pass.

**Comment by vinniefalco** [comment]
Thank you that's perfect!
