### ISSUE TITLE
Enforce minimum version of MSVC compiler

### ISSUE THREAD

**Issue by PROGrand** [vinniefalco/Beast#216]
Usage beast::detail::void_t template for type safety breaks compilation. 
Constructions like
```
template<class T, class M, class = beast::detail::void_t<>>
struct is_Reader : std::false_type {};

template<class T, class M>
struct is_Reader<T, M, beast::detail::void_t<decltype( ... some ... )>>
```
are always interpreted as first definition (false_type).

Removing beast::detail::void_t allows to compile and successive run.
```
template<class T, class M, class = beast::detail::void_t<>>
struct is_Reader : std::false_type {};

template<class T, class M>
struct is_Reader<T, M, decltype( ... some ... )>
```

**Comment by vinniefalco** [comment]
Isn't the latest version is Visual Studio 2015 Update 3? Do you get the same error with the more recent version?

**Comment by PROGrand** [comment]
2015 Update 1. Important tool in my development environment (nvcc from Nvidia CUDA Toolkit actually) does not support updates newer than 1.

**Comment by vinniefalco** [comment]
Visual Studio 2015 Update 1 has significant defects in its support for C++11, such as the bug with SFINAE that you uncovered. I don't have the resources to support those older versions.

**Comment by vinniefalco** [comment]
I'll close this, since its not a sustainable solution.

**Comment by vinniefalco** [comment]
At the least, Beast should contain header mechanics to detect the version of Visual Studio:

`_MSC_VER` and `_MSC_FULL_VER` by version:
14.0 (2015)	1900	190023026
14.0 (2015 Update 1)	1900	190023506
14.0 (2015 Update 2)	1900	190023918
14.0 (2015 Update 3)	1900	190024210

Source:
https://sourceforge.net/p/predef/wiki/Compilers/
