### ISSUE TITLE
Example HTTP program in the documentation does not compile.

### ISSUE THREAD

**Issue by rjahanbakhshi** [vinniefalco/Beast#222]
error: C2039: 'request_v1': is not a member of 'beast::http'
error: C2039: 'response_v1': is not a member of 'beast::http'

**Comment by vinniefalco** [comment]
Yes, I see that. Some of the types were renamed to be more streamlined. Here's the source code for the example program, it should compile (its built as part of the continuous integration so I'm sure it works):
https://github.com/vinniefalco/Beast/blob/master/examples/http_example.cpp

I will update the docs, thanks!

**Comment by rjahanbakhshi** [comment]
Hi Vinniefalco,
Thank you. Yes the one in the example directory compiles and works fine.
