### ISSUE TITLE
fyi - boost::system can be header-only for beast

### ISSUE THREAD

**Issue by larsonmpdx** [vinniefalco/Beast#231]
this trick works (last answer):

http://stackoverflow.com/questions/5089245/boost-asio-as-header-only/40729439#40729439

I can't tell but it might not work for the tests.  Works fine for my application, no need to link to boost::system, the whole thing becomes header-only.

**Comment by vinniefalco** [comment]
Now that is very interesting! I didn't know that!

**Comment by vinniefalco** [comment]
Thinking about it, there's nothing really for me to do here, since Beast is header-only. This is good advice for those looking to integrate Beast in their projects, but there's nothing actionable for me so I'm going to go ahead and close this. Thanks!
