### ISSUE TITLE
How do I put a beast::websocket::stream in a class variable?

### ISSUE THREAD

**Issue by Aidoboy** [vinniefalco/Beast#234]
I create it using `beast::websocket::stream<stream_type&> ws{stream};`, and I have a class variable `std::shared_ptr<beast::websocket::stream<stream_type&>> ws_;` but trying to assign it results in results in:
```
error: no viable overloaded '='
    ws_ = &ws;
    ~~~ ^ ~~~
```
Which I didn't think was a good idea anyway. I tried creating it as a shared_ptr with `std::shared_ptr<beast::websocket::stream<stream_type&>>ws = {stream};`, `std::shared_ptr<beast::websocket::stream<stream_type&>>ws{stream};`,
```cpp
    std::shared_ptr<beast::websocket::stream<stream_type&>>ws;
    *ws{stream};
```
, and 
```cpp
    std::shared_ptr<beast::websocket::stream<stream_type&>>ws;
    ws->{stream};
```
but none of those worked. I have no idea what I'm doing. DOes anyone have any help?

**Comment by Aidoboy** [comment]
I ended up doing this: `ws_ = new beast::websocket::stream<stream_type&>(stream);`

If that's wrong, please tell me.

**Comment by Aidoboy** [comment]
I did this, and I'm pretty sure it's fine. `ws_ = std::make_shared<beast::websocket::stream<stream_type&>>(stream);`

**Comment by vinniefalco** [comment]
Yep, that works, and I was going to suggest it.
