### ISSUE TITLE
Getting `resolve: Host not found (authoritative)` from a valid address.

### ISSUE THREAD

**Issue by Aidoboy** [vinniefalco/Beast#235]
I'm trying to convert [my discord library, Discord++,](https://github.com/Aidoboy/discordpp) from Websocket++ to Beast, as Webscoket++ was (I think) causing random disconnects, and I'm getting a `resolve: Host not found (authoritative)` at the `boost::asio::connect` in 
```
std::string const host = fetchGateway(token);
    boost::asio::ip::tcp::resolver r{asio_ios_};
    boost::asio::ip::tcp::socket sock{asio_ios_};
    boost::asio::connect(sock,
                         r.resolve(boost::asio::ip::tcp::resolver::query{host, "80"}));
```
as well as the SSL example. `fetchGateway(token)` is calling [this Discord API endpoint](https://discordapp.com/developers/docs/topics/gateway#get-gateway) to get the URL `wss://gateway.discord.gg` with CurlPP. It worked with Websocket++, I'm probably doing something very wrong here. Does anyone know what?

**Comment by vinniefalco** [comment]
Hmm....your code looks right. I'm not sure what the problem is, or even if there is a problem. It looks like your program (or computer) is not connected to the Internet, or DNS services are not configured correctly. This StackOverflow question seems to address your use case, maybe it can help?
http://stackoverflow.com/questions/5971242/how-does-boost-asios-hostname-resolution-work-on-linux-is-it-possible-to-use-n

**Comment by Aidoboy** [comment]
I'll give to SO question you linked a read. The part that's really confusing me is that the old Websocket++ version is still making the connection, but this can't.

**Comment by vinniefalco** [comment]
If possible, try to step through websocket++ and see what the API calls are returning, and compare that with what you're getting from your own code.

**Comment by maddinat0r** [comment]
You have to remove the protocol in the gateway URL and use `https` instead of the port. You can take a look at [how I did this here](https://github.com/maddinat0r/samp-discord-connector/blob/master/src/CNetwork.cpp#L96).
I also get regular disconnects from the Discord gateway, and I suspect Discord being at fault here rather than the client library.

**Comment by nbougalis** [comment]
What is the value of `host` in your example? You seem to suggest that it is: `wss://gateway.discord.gg`. If that's true, then this will never work. Can you manually specify `gateway.discord.gg` instead, and see if that works?

**Comment by Aidoboy** [comment]
Thank you everyone! New error, so that's progress, I guess. I now have:
```cpp
// Normal boost::asio setup
    std::string host = fetchGateway(token);
    std::string::size_type protocolPos = host.find("wss://");
    if (protocolPos != std::string::npos) {
        host.erase(protocolPos, 6);
    }
    boost::asio::ip::tcp::resolver r{asio_ios_};
    boost::asio::ip::tcp::socket sock{asio_ios_};
    boost::asio::connect(sock,
                         r.resolve(boost::asio::ip::tcp::resolver::query{host, "https"}));
```
Which results in
```
terminate called after throwing an instance of 'boost::system::system_error'
  what():  upgrade request failed
```
Anyone know what this means?

**Comment by vinniefalco** [comment]
`upgrade request failed` is a Beast error. It looks like you're connecting to their `https` protocol. Try using `query{host, "wss")`

Also, where's the rest of your code? The part that sets up the `beast::websocket::stream`? You're trying to do OpenSSL are you handshaking correctly? Where's the code?

**Comment by Aidoboy** [comment]
I added some debug prints, it's actually failing a few lines later, at the handshake. Give me a sec to try some stuff.

**Comment by Aidoboy** [comment]
I tried `"80"` `"http"` and `"wss`", none of them seemed to work.

[Here's the code in question](https://github.com/Aidoboy/discordpp/blob/beast/src/client.cc#L79)

**Comment by vinniefalco** [comment]
If you want to connect to Secure WebSockets ("wss") you need to use OpenSSL. See:
https://github.com/vinniefalco/Beast/blob/master/examples/ssl/websocket_ssl_example.cpp

**Comment by nbougalis** [comment]
You seem to be using HTTP but trying to talk to an HTTPS server. From everything I can see, discord doesn't allow HTTP. You need to use the SSL-aware Boost ASIO sockets.

**Comment by Aidoboy** [comment]
Ok, I switched back to the SSL code I'd been trying to use with the wss::// clipped off, and it gets through the connections. Now I'm getting `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` which I think is coming from sometime after I tell `asio_ios_` to run. Did I mess up something with my async?

**Comment by vinniefalco** [comment]
Sounds like you have a lot going on there. Consider taking the Beast websocket SSL example as a starting point, change the code to connect to the Discord server, and then slowly adapt the code to suit your needs - this way, you start from something that works.

**Comment by Aidoboy** [comment]
Ok

**Comment by Aidoboy** [comment]
Closing this, since the issue it's about was solved.
