### ISSUE TITLE
handler_ptr issues

### ISSUE THREAD

**Issue by harrishancock** [vinniefalco/Beast#242]
Hey Vinnie, I've been using `handler_ptr` in my own code and ran into three little issues:

1. There is no way to check whether or not a `handler_ptr` is valid. `ptr.get() != nullptr` cannot be used, because that dereferences `p_`, which may be null.

   An `explicit operator bool() const { return p_ != nullptr && p_->t != nullptr; }` would suffice, but it also occurred to me that perhaps `get()` should `return p_ != nullptr ? p_->t : nullptr`? That would prevent calling `ptr.get()` on a moved-from `ptr` from crashing.

   My use case is that I'd like to use assertions to check for programming errors in my code.

2. Much less important, but an `element_type = T` member typedef would be nice. I reached for one while specializing a traits class and missed it from the standard smart pointers.

3. `make_handler_ptr` seems to have missed the documentation. Perhaps Doxygen ignores friend function declarations, and needs them declared outside the class as well?

Thanks!

**Comment by vinniefalco** [comment]
Great suggestions, I agree with everything. Not sure what happened with `make_handler_ptr`. One thing I should point out, the "quick reference" is maintained by hand, and I did forget to put `make_handler_ptr` in there:
https://github.com/vinniefalco/Beast/blob/master/doc/quickref.xml#L178

However, that doesn't explain why `make_handler_ptr` is not appearing in the automatically generated Index:
http://vinniefalco.github.io/beast/beast/index.html

**Comment by vinniefalco** [comment]
This will go in to *1.0.0-b25*
https://github.com/vinniefalco/Beast/commit/d3368d0b9f1f8392f9ee2a74830c210f28720f36

**Comment by harrishancock** [comment]
Thanks for the quick turn around! Two things you may or may not have already spotted:

1. gcc 5.4 complains thusly:
   ```
   /.../beast/core/handler_ptr.hpp: In function ‘beast::handler_ptr<T, Handler> beast::make_handler_ptr(Handler&&, Args&& ...)’:
   /.../beast/core/handler_ptr.hpp:189:12: error: ‘make_handler_ptr_helper’ was not declared in this scope
     return make_handler_ptr_helper<T, Handler>(
            ^
   ```
   and again on line 198.

   I copied and pasted the friend declarations verbatim (minus the `friend` word) outside the class scope, above `make_handler_ptr` definitions, and it all compiled and worked correctly. (Could the two functions be folded into one? I presume some compiler gave you a pragmatic reason to separate them.)

2. `unit_test/dstream.hpp` crept into `websocket/impl/write.ipp`

**Comment by vinniefalco** [comment]
Updated: https://github.com/vinniefalco/Beast/commit/a44785abc7cdc6b67afd46c25dc820797d512560

**Comment by vinniefalco** [comment]
Note that the API has changed slightly - for the better I hope!

**Comment by harrishancock** [comment]
Looks good -- I agree, for the better! Thanks again. :)
