### ISSUE TITLE
Websocket ping callback

### ISSUE THREAD

**Issue by Codeazure** [vinniefalco/Beast#248]
I would like to be able to set a ping control frame callback. This is so the client can tell if it is still receiving them from the server periodically by using a timer set when the last ping was received. I don't need to do anything in Beast when this happens - I'm happy with the auto-pong functionality. I just want to know when it happens.

At present, the only strategy I can see is that both client and server send periodic ping messages to confirm the other side is still there when the pong is received. Is this the common approach for most WebSocket applications?

**Comment by vinniefalco** [comment]
We can do one of two things:
1. Add a "ping callback", or
2. Call the pong callback when a ping is received. The pong callback could have an aditional bool indicating if the control frame is a ping versus a pong.

**Comment by Codeazure** [comment]
Either one would be great. With option 2, would you change its name to on_ping_pong() in that case or just keep the current on_pong? Maybe cleaner to go with option 1, because then you don't break existing applications and then the two callbacks are clearly named.

I don't mind either solution - you choose which suits the design best.

**Comment by vinniefalco** [comment]
Please give this a try
https://github.com/vinniefalco/Beast/commits/b27

**Comment by Codeazure** [comment]
Thanks for doing that so quickly. I'll test that as soon as possible.

In the websocket documentation, it says : "'is_pong' set to 'true' if a ping was received". I assume this is a typo & you meant the other way around?

**Comment by vinniefalco** [comment]
It should read "is_pong is set to `true` if a pong was received`

**Comment by vinniefalco** [comment]
I fixed the documentation (thanks!), here's a preview:
http://vinniefalco.github.io/stage/beast/
