### ISSUE TITLE
Parser non-deterministically fails to read body

### ISSUE THREAD

**Issue by mika-fischer** [vinniefalco/Beast#257]
There seems to be a strange bug, when parsing header and body subsequently. Example code can be found here: [coroutine version](https://gist.github.com/mika-fischer/cb93b1071d9eea492f27234f7fb6d1b2) [callback version](https://gist.github.com/mika-fischer/a54a68769985afe0f22967881513cbb8).

The problem manifests for body sizes larger than 64k. For body sizes smaller than that I've not been able to trigger the bug.

So, generate a file with 64k or more, `dd if=/dev/zero of=test.bin bs=1k count=64`. Then use curl to post it to the server: `while curl --data-binary @test.bin -H 'Expect:' http://127.0.0.1:8081/; do; done;`

Shortly, curl will exit with `curl: (55) Send failure: Connection reset by peer`.

The output of a working request is:
```
New connection

Waiting for request...
Received headers:
POST / HTTP/1.1
Host: 127.0.0.1:8081
User-Agent: curl/7.52.1
Accept: */*
Content-Length: 65536
Content-Type: application/x-www-form-urlencoded

Buffer size after headers: 361
Body size: 65536

Waiting for request...
Error: End of file
Connection closed
```

But often, beast will think there is no body or it has already read it. It will then immediately send the response and try to read another request, which fails, since the client is still sending the body data.

```
New connection

Waiting for request...
Received headers:
POST / HTTP/1.1
Host: 127.0.0.1:8081
User-Agent: curl/7.52.1
Accept: */*
Content-Length: 65536
Content-Type: application/x-www-form-urlencoded

Buffer size after headers: 0
Body size: 0

Waiting for request...
Error: bad method
Connection closed
```

Any idea what's wrong here?

**Comment by vinniefalco** [comment]
Thank you for your report. I am investigating. But if you want to try something real quick, try changing `asio::streambuf` to `beast::streambuf` and see if that fixes it. You'll have to include `<beast/core/streambuf.hpp>`

**Comment by mika-fischer** [comment]
I tried both already, actually. Same issue. Thanks for taking a look!

**Comment by vinniefalco** [comment]
Does this happen only when the body is parsed separately? What if you read the entire message in one go?

**Comment by mika-fischer** [comment]
When I use only the `parser_v1` to parse everything in one go, everything works as expected.

**Comment by vinniefalco** [comment]
We have tracked the problem down to a bug when a parser is constructed from the header parser. Working on a fix...

**Comment by mika-fischer** [comment]
Awesome, thanks, that fixed it!
