### ISSUE TITLE
Consider distribution of the library using vcpkg

### ISSUE THREAD

**Issue by jhruby** [vinniefalco/Beast#269]
Hi,
It would be very cool to see your library distributed through vcpkg channel. 

Jan

**Comment by vinniefalco** [comment]
Thanks for your interest in Beast! I tried going through the steps for vcpkg but it was a bit too complex for me. But if you'd like to package it up (or anyone else who wants to volunteer) I would be very appreciative!

**Comment by jhruby** [comment]
I can look into that and package it. I would than need the url for certain stable version of the package. It should not point to master probably.

**Comment by vinniefalco** [comment]
Hmm... well, Beast is still in beta. There's a little more interface work to do before I can consider calling a 1.0 version. Specifically this: https://github.com/vinniefalco/Beast/issues/154

**Comment by jhruby** [comment]
Well there are other betas in vcpkg. I don't see it as a problem.

**Comment by vinniefalco** [comment]
Oh! Okay, well when **b29** passes review I will create a tag for **v1.0.0-b29** and we can use that. Thanks!

**Comment by jhruby** [comment]
Awesome :-)

**Comment by vinniefalco** [comment]
I've created a new tag, its called **v1.0.0-b30** if you would like to try setting up the package! If you need to add files to the repository just submit a pull request. Thanks!

**Comment by jhruby** [comment]
Hi, I'll look into that.

**Comment by jhruby** [comment]
I just created a pull request for Microsoft.
https://github.com/Microsoft/vcpkg/pull/781

**Comment by vinniefalco** [comment]
@jhruby You did such a wonderful job on this could you possibly be interested in doing the same for NuDB? Its quite similar to Beast in structure: https://github.com/vinniefalco/NuDB

**Comment by jhruby** [comment]
Sure I can do it :)

**Comment by vinniefalco** [comment]
Cool! I pushed a tag for `1.0.0` of the library

**Comment by vinniefalco** [comment]
This looks like it's done, thanks!
