### ISSUE TITLE
Can Beast be used with the non-boost version of Asio?

### ISSUE THREAD

**Issue by crujose** [vinniefalco/Beast#278]
http://think-async.com/Asio/AsioAndBoostAsio
https://github.com/chriskohlhoff/asio

I see there are some direct includes of boost headers (e.g. https://github.com/vinniefalco/Beast/blob/master/include/beast/core/error.hpp#L11 ) but I was wondering how much of a rabbit hole it would be to carve out the dependency on boost.

**Comment by djarek** [comment]
@crujose 
I believe there are some classes that would have to be replaced without boost (optional/tribool, don't remember which one).

**Comment by vinniefalco** [comment]
Beast uses other parts of boost such as Boost.Intrusive, a smattering of utilities. It is in theory possible. But I don't have the resources to maintain a standalone-Asio fork of Beast. And I am trying to get Beast into boost - if Beast passes a formal review then my workload will probably triple!

**Comment by crujose** [comment]
Fair enough!  I was mostly hoping for a header-only option that didn't need additional linking which is almost the case here except for boost-system.  I'm probably being too nit-picky though.

**Comment by vinniefalco** [comment]
I believe there is a way to eliminate the boost-system dependency, there's a macro for it, try looking through the Beast issues.

**Comment by vinniefalco** [comment]
I found it! https://github.com/vinniefalco/Beast/issues/231

**Comment by vinniefalco** [comment]
Since there's nothing for me to do here yet, I'm going to close it - thanks!
