### ISSUE TITLE
http::write do not send message unless i close socket

### ISSUE THREAD

**Issue by zhaohuaxishi** [vinniefalco/Beast#281]
i use beast to write http server and client, my client block if i do not close the sock on server side.

on client side, i send http request and wait response like this:

```
RequestType request;
// setup request
beast::http::write(sock, request);

beast::streambuf buffer;
ResponseType resp;
// setup response
beast::http::read(sock, buffer, resp);    // this function block
```

on server side, i read request and write response like this:

```
RequestType request;
beast::http::read(sock, buffer, request);

auto response = handle_request(request);
beast::http::write(sock, response);
// sock->close();
```

if i do not call `sock->close()` on server side,  client call of `beast::http::read(sock, buffer, resp)` will block.

Any help would be appreciated.

**Comment by vinniefalco** [comment]
Are you specifying HTTP/1.0 as the version?

**Comment by zhaohuaxishi** [comment]
request looks like this:
```
beast::http::request<beast::http::string_body> context_request;
context_request.version = 11;
context_request.method = "SETUP";
context_request.url = "/context";
context_request.fields.insert("name", "beast");
```

and response looks like this:
```
beast::http::response<beast::http::string_body> resp;
resp.version = request.version;
resp.status = 200;
```

and thank you for help @vinniefalco

**Comment by vinniefalco** [comment]
HTTP responses need a Content-Length for 200 level status code. Try:
```
resp.fields.insert("Content-Length", "0");
```
alternatively you could try
```
beast::http::prepare(resp);
```
Before calling `write`. See:
http://vinniefalco.github.io/beast/beast/ref/http__prepare.html

**Comment by zhaohuaxishi** [comment]
it works! thank you very much. but if i define response like this:
```
beast::http::response<beast::http::empty_body> resp;
```
`beast::http::read` will complain about `Body has no reader`, is that means i can not use `beast::http::empty_body` to instance `beast::http::response`, if not, then how should i implement the reader

**Comment by vinniefalco** [comment]
1. `empty_body` was removed a few versions ago, you should update to the tip of the **master** branch

2. Use `beast::http::response_header` if you are not expecting a body..

**Comment by zhaohuaxishi** [comment]
Got it, again thanks for help.
