### ISSUE TITLE
Why are the build badges broken?

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#283]
Can someone please tell me what happened? There were no changes to README.md but now the badges are broken...

See the top of this page
https://github.com/vinniefalco/Beast/blob/master/README.md

**Comment by HowardHinnant** [comment]
I experienced a similar failure this morning.  I'm not sure of the cause.  I fixed it by trial and error with this:  https://github.com/HowardHinnant/date/commit/5eff31acdd1e1b67577d486155088951e63a70eb

**Comment by vinniefalco** [comment]
So now you're also better than me at fixing Markdown...

**Comment by vinniefalco** [comment]
Testing:

[![Join the chat at https://gitter.im/vinniefalco/Beast](https://badges.gitter.im/vinniefalco/Beast.svg)](https://gitter.im/vinniefalco/Beast?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [![Build Status](https://travis-ci.org/vinniefalco/Beast.svg?branch=master)](https://travis-ci.org/vinniefalco/Beast)

**Comment by vinniefalco** [comment]
WEW LAD Removing the newlines fixed it! Unfortunate, because if you have a whole row of badges they have to all go on the same line of markdown.
