### ISSUE TITLE
[http branch] async_read of http::request<http::string_body> has empty body

### ISSUE THREAD

**Issue by mika-fischer** [vinniefalco/Beast#291]
Reading the whole request with a `message_parser<true, string_body, fields>` works fine.

**Comment by vinniefalco** [comment]
You gave me a panic, but then I saw it was in the http branch!

**Comment by vinniefalco** [comment]
I pushed this fix to the branch:
https://github.com/vinniefalco/Beast/commit/6e8c14d6abb458c96363c18414e4296a853ebcba

**Comment by vinniefalco** [comment]
This should be fixed now, thanks
