### ISSUE TITLE
Passing additional HTTP headers to handshake/async_handshake request

### ISSUE THREAD

**Issue by thoism** [vinniefalco/Beast#292]
Is there a way to pass additional headers to the handshake request?

Examples:
1. [Java](https://blog.heckel.xyz/2014/10/30/http-basic-auth-for-websocket-connections-with-undertow/)
2. [nodeJS](https://appsaloon.be/blog/websocket-basic-authorization-in-node-js/)

Thank you

**Comment by vinniefalco** [comment]
Yep, that's entirely possible! See:

https://github.com/vinniefalco/Beast/issues/70

Let me know if you have questions!

**Comment by thoism** [comment]
Thank you very much!
