### ISSUE TITLE
Compilation errors with Boost 1.64

### ISSUE THREAD

**Issue by cdmh** [vinniefalco/Beast#296]
Currently in Beta, Boost 1.64 breaks Beast

Using VC14.1 (Visual Studio 2017)

`Beast\include\beast/websocket/detail/decorator.hpp(105): error C2280: 'boost::basic_string_ref<char,std::char_traits<char>>::basic_string_ref<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': attempting to reference a deleted function`

`Beast\include\beast/websocket/detail/decorator.hpp(118): error C2280: 'boost::basic_string_ref<char,std::char_traits<char>>::basic_string_ref<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': attempting to reference a deleted function`

`Beast\include\beast/websocket/impl/stream.ipp(189): error C2280: 'boost::basic_string_ref<char,std::char_traits<char>>::basic_string_ref<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': attempting to reference a deleted function`

`Beast\include\beast/http/basic_fields.hpp(266): error C2280: 'boost::basic_string_ref<char,std::char_traits<char>>::basic_string_ref<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': attempting to reference a deleted function`

**Comment by HowardHinnant** [comment]
This _should_ be fixed by this: http://lists.boost.org/Archives/boost/2017/03/234022.php but isn't yet.

**Comment by vinniefalco** [comment]
Is this still an issue in the release version of Boost 1.64.0?

**Comment by vinniefalco** [comment]
It looks like this is fixed so I'll close the issue. Please re-open it if a problem remains, thanks!
