### ISSUE TITLE
 error: C2338 Reader requirements not met

### ISSUE THREAD

**Issue by Lifeda92** [vinniefalco/Beast#308]
Hello, i tried use your library Beast on VSE 2015, boost v. 1.62. When i tried to compile example code HTTP GET, WebSocket (http://vinniefalco.github.io/beast/beast/example.html), i got an error: C2338 Reader requirements not met. How can i fix it? Help me, please, thx.

**Comment by vinniefalco** [comment]
Which version of Beast are you using? You can tell by looking at `include/version.hpp`, or looking at the tip commit message.

**Comment by Lifeda92** [comment]
1.0.0-b32

**Comment by vinniefalco** [comment]
Please try **1.0.0-b34**, currently at the tip of the _master_ branch?

**Comment by Lifeda92** [comment]
Tried 1.0.0-b34. Now this error: C4996	'std::equal::_Unchecked_iterators::_Deprecate': Call to 'std::equal' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'	project	c:\program files\microsoft visual studio 14.0\vc\include\xutility	2983

**Comment by vinniefalco** [comment]
I'm not sure why you're having so much trouble. Are you using CMake to build the Visual Studio project files (.vcxproj files)? What is your exact command line to invoke CMake? The build scripts that come with Beast set `_SCL_SECURE_NO_WARNINGS`, see:
https://github.com/vinniefalco/Beast/blob/6d5547a32c50ec95832c4779311502555ab0ee1f/CMakeLists.txt#L10

**Comment by vinniefalco** [comment]
Are you still having problems? If so, feel free to reopen this issue. Or if you have a new problem, create a new issue - thanks!
