### ISSUE TITLE
Is there support for basic authentication

### ISSUE THREAD

**Issue by randallvenhola** [vinniefalco/Beast#312]
This looks very interesting. I am looking at building a REST client using Beast. I read through the documentation and examples and I don't see this - is basic authentication supported? Or do I need to encode the user/password in the header and then manage the challenge/response?

**Comment by vinniefalco** [comment]
You have to manage the headers yourself. Consider making your code into a library that other people can use!

**Comment by vinniefalco** [comment]
It looks like this issue is resolved, I'll go ahead and close it. If you have another issue, or you think that there is more to this issue that needs to be discussed please feel free to open a new issue or re-open this one, thanks!
