### ISSUE TITLE
Type narrowing error on android [-Wc++11-narrowing]

### ISSUE THREAD

**Issue by eakraly** [vinniefalco/Beast#344]
Compiling beast 1.0.0-b36 using `LOCAL_CPPFLAGS += -std=c++14 -Wall` with android NDK r14b gets this:

> 
\~/beast/http/detail/rfc7230.hpp:241:9: error: constant expression evaluates to -1 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 0
        ^\~

\~/beast/http/detail/rfc7230.hpp:241:9: note: insert an explicit cast to silence this issue
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 0
        ^\~
        static_cast<char>( )
>

**Comment by vinniefalco** [comment]
Thanks for the report, the fix will go in to **b37**, would you consider reviewing the pull request and commenting on anything you want?
https://github.com/vinniefalco/Beast/pull/341

**Comment by vinniefalco** [comment]
I see, it looks like your build environment has `char` as unsigned! I have added the compiler switch `-funsigned-char` to one of the CI build targets so I can reproduce your issue (and be notified if it ever happens again after I fix it!)
