### ISSUE TITLE
What if peer doesn't reply with Close Frame during websocket closing handshake?

### ISSUE THREAD

**Issue by vchang-akamai** [vinniefalco/Beast#365]
To close a websocket connection, we call beast::websocket::async_close() (or close()) to send the Close Frame to the peer to initiate the closing handshake  Then we need to keep calling async_read() (or read()) until receiving error::closed which indicates that the peer has replied with its Close Frame.

What if the peer is misbehaving (maybe DoS abuse) and never sends its Close Frame? Does Beast enforce any timeout limit for this?  Or we need to add our own?

**Comment by vinniefalco** [comment]
You need to handle that timeout yourself

**Comment by vchang-akamai** [comment]
Ok, thanks for the info
