### ISSUE TITLE
.. beast/core/to_string.hpp: No such file or directory

### ISSUE THREAD

**Issue by Ivers87** [vinniefalco/Beast#385]
may be I'm doing something wrong, but i downloaded ZIP, and there is no to_string.hpp in 
\Beast-master\include\beast\core.

So, i have compile error.

**Comment by vinniefalco** [comment]
Were you calling `to_string` in your code, and then you updated to a newer Beast and got the compile error? The function `to_string` has been removed. If you want to convert buffers to a string, use `boost::lexical_cast` and the `buffers` function. Like this:

```
    boost::lexical_cast<std::string>(beast::buffers(b));
```

Where **b** is your **ConstBufferSequence**

**Comment by Ivers87** [comment]
Thanks for answer. 
I started to work with beast yesterday, downloaded repository, and took an example of websockets from here:

https://github.com/vinniefalco/Beast

**Comment by vinniefalco** [comment]
Oh! It looks like I forgot to update the README.md for these changes, sorry about that! Please use this file instead:
https://github.com/vinniefalco/Beast/blob/master/examples/websocket_example.cpp

**Comment by Ivers87** [comment]
Now, everything compiled and builded well, thanks. But, in main page https://github.com/vinniefalco/Beast#usage, there is still wrong example =)

**Comment by vinniefalco** [comment]
Yes, I have not yet merged the fixes to the *master* branch
