### ISSUE TITLE
Can not beast::http::read with boost::asio::streambuf

### ISSUE THREAD

**Issue by qwertzui11** [vinniefalco/Beast#386]
`beast::http::read(stream, cache, parser);`
does not compile with 
```
using cache_type = boost::asio::streambuf;
cache_type streambuf;
beast::buffers_adapter<cache_type::mutable_buffers_type> cache(streambuf.prepare(512));
```
but I compiles with
`boost::asio::mutable_buffer cache;`
According to the documentation `buffers_adapter` takes a `MutableBufferSequence` which `boost::asio::streambuf::prepare` fullfills and wraps it to a `DynamicBuffer`. 
Have I missunsterstood something?
Im using gcc6.1 on ubuntu 17.04.

**Comment by vinniefalco** [comment]
Hmm... I think what you're doing should work, but I have not tried it. And there could very well be a bug. I will look into it right away!

**Comment by vinniefalco** [comment]
I tried the code you provided and it compiles for me:
https://github.com/vinniefalco/Beast/commit/f9db7676beff74a908dff1df7c137ec7b658833b

Do you have any more information? Can you include the output containing the compilation error? What version of Boost? What version of Beast? Thanks!

**Comment by vinniefalco** [comment]
Hmm... the code compiles correctly under gcc6.x
https://travis-ci.org/vinniefalco/Beast/jobs/235713266

I will need more information in order to figure it out.

**Comment by qwertzui11** [comment]
the error occurs on compiling the line
`beast::http::read(...)`

I set up a quick project
https://github.com/qwertzui11/beast_issue386
Because I'm not at work the compiler now is g++5.4.0, Boost-1.58 and ubuntu 16.04
At work the same error occurs with g++6.1, Boost-1.64 and ubuntu 17.04
Beast version is "master" (v44?)

Another issue occured with g++5.4.0
when I replace in https://github.com/qwertzui11/beast_issue386/blob/master/test.cpp line 1 and 2 with 
`#include <beast/core.hpp>` it doesnt compile because of the header files.

**Comment by vinniefalco** [comment]
Yes! I was able to reproduce your defect. I believe this branch fixes your problem please try it:
https://github.com/vinniefalco/Beast/commits/v44

**Comment by qwertzui11** [comment]
I tried and succeeded with both my compile issues. Only tested g++5.4, but I'm confident, g++6.1 won't have any issues.
Thx a lot!

**Comment by vinniefalco** [comment]
Thank you for finding this bug!

**Comment by qwertzui11** [comment]
It seems like it doesn't compile if the `buffers_adapter` is a rvalue. Code says more than a 100 words:
https://gitlab.com/qwertzui11/beast_issue386/blob/79a49b7a536a3db7c5cd364ef4ad715493558ed9/test.cpp#L21
build_log:
https://gitlab.com/qwertzui11/beast_issue386/builds/18426413
Have I got something wrong? thx for your time!

**Comment by vinniefalco** [comment]
Hmm the first link doesn't work

**Comment by qwertzui11** [comment]
it works no, sry, i failed in setting the premissions correctly

**Comment by vinniefalco** [comment]
```
beast::http::read(
    stream,
    beast::buffers_adapter<cache_type::mutable_buffers_type>(streambuf.prepare(512)),
    parser);
```

You're trying to bind a temporary to a non-const reference parameter? tsk tsk! I think that's not valid C++!

**Comment by qwertzui11** [comment]
> tsk tsk!
Ur right, lol, fail.

**Comment by vinniefalco** [comment]
I wish I could say that I have never tried to do such a thing...

**Comment by vinniefalco** [comment]
That is a fascinating use-case though. What are you trying to accomplish? You will limit the maximum size of the header that way, to 512 bytes.

**Comment by qwertzui11** [comment]
I'm just playing around with asio::streambuf and beast - `512` is a random number.
