### ISSUE TITLE
single sign on

### ISSUE THREAD

**Issue by octopus-prime** [vinniefalco/Beast#426]
does/will beast http/websocket support any kind of single sign on (e.g. spnego)?

**Comment by vinniefalco** [comment]
No, but someone else can write it as a library using Beast's `message` container and then people could import it. Maybe you could do that!

**Comment by vinniefalco** [comment]
Is this still an issue?

**Comment by octopus-prime** [comment]
This ticket was just a question and you gave an answer -> issue closed.
