### ISSUE TITLE
Implicit fallthroughs

### ISSUE THREAD

**Issue by niklas88** [vinniefalco/Beast#437]
On master, when compiling with GCC 7.1.1 -Wimplicit-fallthrough is turned on and triggered by a lot of switch statements which by the looks of it are supposed to fall through (e.g. in serializer.ipp).

Sadly the [[fallthrough]] attribute to mark these cases explicitly is only available from C++17 onwards. So I'm not sure what the best fix is.

**Comment by 2underscores-vic** [comment]
> So I'm not sure what the best fix is.

-Wno-implicit-fallthrough ?

**Comment by vinniefalco** [comment]
I could add a macro
```
#define BEAST_FALLTHROUGH [[fallthrough]]
```

And then do the usual boost/config.hpp thing. Its better not to disable warnings. @glenfe is there a Boost config setting for fallthrough?

**Comment by vinniefalco** [comment]
Oh hey!
http://www.boost.org/doc/libs/1_64_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_c__17_features_not_supported

`BOOST_FALLTHROUGH` is a thing!

**Comment by vinniefalco** [comment]
I tried to get GCC 7.x going on Travis but I am not familiar with Linux and the gcc packaging so I was unsuccessful. If someone wants to add a Travis matrix target for GCC 7.x that would really be helpful!

**Comment by glenfe** [comment]
The 1.64 definition of BOOST_FALLTHROUGH won't help you with gcc 7.1. We can make sure it will, for 1.65 though.

**Comment by vinniefalco** [comment]
@2underscores-vic Please consider participating in the Boost formal review for Beast, which starts on July 1st. All you need to do is sign up to the Boost developers mailing list (https://lists.boost.org/mailman/listinfo.cgi/boost) ahead of time and listen for the announcement from the review manager. Your review is vital to the health and success of the library - whether you have positive things to say, or negative things to say, feedback is the only way for Beast to get better!
