### ISSUE TITLE
Rename websocket server sources

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#46]
To "server" instead of "peer", so they are more easily recognized

**Comment by vadz** [comment]
Sorry but does this mean that there is already an example of WebSocket server somewhere? I was looking for one just to see how should it look like but couldn't find one, did I really miss it? If not, and it really doesn't exist (yet?), I'd just like to mention that it would be nice to have a matching example server for the `examples/websocket_example.cpp` to speak to.

**Comment by vinniefalco** [comment]
And this is why we need to rename the source files :-)

See
https://github.com/vinniefalco/Beast/blob/master/test/websocket/websocket_async_echo_peer.hpp

**Comment by vinniefalco** [comment]
I should probably put either a copy of the echo server or a new server program into the examples/ directory to make it easier to find.

**Comment by vadz** [comment]
Yes, this would have helped me. Of course, searching for just 30 seconds longer would have helped me as well :-/

**Comment by vinniefalco** [comment]
@vadz I'd be very interested in hearing feedback from you on your experiences with the library, and if I can help answer questions I'm available. Public feedback or private (my email is on my GitHub profile page).
