### ISSUE TITLE
"Access-Control-Allow-Origin" header missing in field.hpp

### ISSUE THREAD

**Issue by niklas88** [vinniefalco/Beast#473]
This header is needed for cross domain requests, a good reference can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)

**Comment by vinniefalco** [comment]
Should we just add everything in the "Provisional Message Header Field Names" from https://www.iana.org/assignments/message-headers/message-headers.xhtml ?

Would you like to try your hand at adding them? Just append the list from "https://www.iana.org/assignments/message-headers/message-headers.xhtml" to this file:
https://github.com/vinniefalco/Beast/blob/master/scripts/field.txt

Then run this nifty script:
https://github.com/vinniefalco/Beast/blob/master/scripts/make_field.sh

To produce the three chunks of source code (field.hpp, field.ipp, and field.cpp). You'll have to manually adjust the size of the array in the header file

Great way to get your name in the commit log :) :) 

Or I can do it, either way works.

**Comment by vinniefalco** [comment]
I did it. This will go into version 56

**Comment by niklas88** [comment]
Thanks 👍 I'm in Europe and when I wrote the issue I had already been working for quite some time.
