### ISSUE TITLE
sync io operations should reset error codes

### ISSUE THREAD

**Issue by Inphi** [vinniefalco/Beast#478]
### Version of Beast
55

When reusing error codes across multiple io operations, beast may terminate the io operation because the error state was previously set. This necessitates the user to always reinitialize the error_code prior to doing io. This behavior is unexpected as boost::asio will reinitialize the error_code before possibly writing to it.

```cpp
response.body.more = true;
boost::system::error_code ec;
auto sr = beast::http::make_serializer(response);
beast::http::write(sock, sr, ec);
// ec is now need_buffer
beast::http::write(sock, sr, ec);
// write fails here because ec was already set; ec is still need_buffer
ec = {};
beast::http::write(sock, serializer, ec);
// write is good again
```

**Comment by vinniefalco** [comment]
I just had a look through the Asio source code, I think you might be right about this one!

**Comment by vinniefalco** [comment]
This is a massive headache because I have to study every function. I **think** the rule works like this:

If a function has `error_code& ec` as a parameter, it must do one of the following

* Call a function that takes the error code
* Set the error code to indicate an error
* Clear the error code

**Comment by niklas88** [comment]
Sadly I have absolutely no idea how boost::asio errors are supposed to work, using Beast is actually my first contact with boost::asio.

**Comment by vinniefalco** [comment]
>Beast is actually my first contact with boost::asio.

Scandalous!
