### ISSUE TITLE
Don't require BOOST_ROOT and BOOST_INCLUDEDIR when installing boost with brew

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#480]
Why do these variables have to be set? Maybe they don't?

**Comment by xsacha** [comment]
This is only because you install from a unzipped package rather than searching system.
In fact, you have disabled system libraries from being found:
https://github.com/vinniefalco/Beast/blob/master/CMakeLists.txt#L51

**Comment by vinniefalco** [comment]
Should I remove that line? What do you suggest to fix this?

**Comment by xsacha** [comment]
Those root and includedir are needed on jenkins for extracted boost.
Otherwise just install libboost.

**Comment by vinniefalco** [comment]
Setting this to `ON`
```
set (Boost_NO_SYSTEM_PATHS ON)
```
only skips searching system paths, it still looks in BOOST_ROOT and BOOST_INCLUDEDIR, see:
https://lists.gnu.org/archive/html/discuss-gnuradio/2011-12/txta1SOQqu6kA.txt

The question becomes then, why skip the system paths?

**Comment by xsacha** [comment]
Yeah I do not know why it was skipping system paths. I just remove it when I need to actually use it. I assumed there was a reaaon.

**Comment by vinniefalco** [comment]
I'm not a cmake expert by any means I just keep hacking away at it until it works!  I must have copied that line from somewhere...
