### ISSUE TITLE
Docker requirement for documentation

### ISSUE THREAD

**Issue by celavek** [vinniefalco/Beast#499]
Hi,

This is not an issue but more if a question. Why the documentation requires usage of Docker?
That is quite a big overhead. I just want to read through the docs and I have to build a whole 
Docker image which takes quite some time. I do not see the benefit. Why not plain Doxygen usage or 
Sphinx or ... ?

Thanks

**Comment by vinniefalco** [comment]
That README is out of date, I will remove it.

**Comment by celavek** [comment]
Thanks for the answer.

You mean I just built a Docker image and all that jazz and there was a simpler way of getting the doc ? :)

**Comment by vinniefalco** [comment]
Yes there's a much simpler way of getting the doc, just go to
http://vinniefalco.github.io/beast/index.html
