### ISSUE TITLE
Bug in base64 decoder

### ISSUE THREAD

**Issue by hoditohod** [vinniefalco/Beast#500]
Base64 inverse table for entry for 65 'A' is -1, whereas it should be 0.

base64.hpp:69

### Version of Beast
54

### Steps necessary to reproduce the problem
N/A

### All relevant compiler information
N/A

**Comment by vinniefalco** [comment]
willfix

**Comment by vinniefalco** [comment]
How did you find that? Good job by the way :)

**Comment by hoditohod** [comment]
Well, uhm... I use bits and pieces from the beast::detail namespace... don't tell anyone!

**Comment by vinniefalco** [comment]
I added a much stronger test, it should make sure this never happens again
