### ISSUE TITLE
Is it possible to read WebSocket Upgrade request header on server side?

### ISSUE THREAD

**Issue by onto** [vinniefalco/Beast#501]
I need to check Origin field from request header (filter websocket clients on server somewhere on `websocket::stream::async_accept` call), but it seems there no way to it now. Is it?

**Comment by hoditohod** [comment]
When you accept a connection you first read a plain http request and then check if it's an upgrade request, if it is, then start a websocket handshake. You can access all the headers from the first http request.

**Comment by vinniefalco** [comment]
Covered in the docs :)
http://vinniefalco.github.io/beast/beast/websocket/server.html

**Comment by vinniefalco** [comment]
Use this overload
http://vinniefalco.github.io/beast/beast/ref/beast__websocket__stream/async_accept/overload4.html

**Comment by onto** [comment]
Thanks, it works. 👍

**Comment by vinniefalco** [comment]
Another satisfied customer, cha-ching!!
