### ISSUE TITLE
Design: Authentication

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#529]
The question has been raised, what would an library that handles authentication look like? Here's a start
```
/** Returns `boost::indeterminate` if a response indicates that authentication is needed

    @return `false` if the response does not indicate 401 Unauthorized. `true` if the
    response indicates 401 Unauthorized and no WWW-Authentication field is present.
    Otherwise, the function returns `boost::indeterminate`.
*/
template<class Body, class Fields>
boost::tribool
is_unauthorized(response<Body, Fields> const& res);
```

When the client calls this function and it returns `true` then this function can be used to fill out a structure with information:
```
/** Fill in a `challenge_info` structure from the authentication requirements of a response
*/
template<class Body, class Fields>
std::expected(challenge_info, std::error_code)
get_challenge(response<Body, Fields> const& res);
```

**Comment by octopus-prime** [comment]
Or something like this:

template<class Derived>
class authentication_handler
{
  challange_response
  on_challange(challange_request req);
}

called if status 401 and header field "WWW-Authentication: ..."

So somebody could implement this interface, if he knows to handle gssapi c-hell :-)

But who calls this interface? Who listens for the status 401 and header field "WWW-Authentication: ..."?

**Comment by vinniefalco** [comment]
>But who calls this interface?

Whoever is implementing a client!

**Comment by vinniefalco** [comment]
This is outside of the scope of Beast for now, closing
