### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#53]
The README.md needs a section with complete instructions for building and running the tests and examples. Especially how to install Boost with bjam in the path.

**Comment by LovelyHorse** [comment]
I'm having a bit of an issue issue with exactly this, any tips on how to include the header files with CMakeList?

**Comment by vinniefalco** [comment]
I'm not sure I understand. Are you trying to build the tests and examples? From the root directory of Beast, do this:
```
mkdir bin
cd bin
cmake ..
```
The bin/ directory will now contain a Makefile, or a Visual Studio project file depending on your configured build tools.

Or are you asking me how to set up *your* CMakeLists.txt in order to use Beast? In that case, just add a line to your CMakeLIsts.txt to add the `include/` directory to be searched by the compiler. Your include lines for Beast would look like this:

```
#include <beast/websocket.hpp>
```

**Comment by LovelyHorse** [comment]
Thanks for that @vinniefalco. When trying building cmake wasn't playing nicely so I just assumed I had to build it another way (having seen the scripts). 

In the end I figured it out, and have some requirements to add:

- cmake > v3.20
- libpthread 
- boost > v1.58 (needs to be version 1.58 or later to make use of the endian library, ubuntu 14.04 repos only have up to 1.55 - so building from source is necessary). 

I'm happy to go ahead and update the README to include the above and be more novice friendly if you would like?

**Comment by vinniefalco** [comment]
Sure, I would love an update to the README.md!

One thing though, keep in mind that Beast is header-only so there's nothing to build except your own project. The only things that you build for Beast are the examples and the unit tests, but those are not required to use the library. Or are you talking about building your own executable that uses Beast?

**Comment by vinniefalco** [comment]
Merged, thanks for the contribution!
