### ISSUE TITLE
Design: Cookies (Client)

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#530]
The question is raised on what an API might look like for handling client cookies. Here it is
```
/** Stores cookies.

    This class stores cookies acquired in HTTP responses or persisted,
    and fills in cookie fields for outgoing HTTP requests.
*/
template<class Derived>
class cookie_jar
{
public:
    /** Extract cookies from an HTTP response.

        This function scans the fields in the response and updates
        stored cookies according to the Set-Cookie fields.

        @param res The response to scan.
    */
    template<class Body, class Fields>
    void
    extract(response<Body, Fields> const& res);

    /** Add stored cookies to an HTTP request

        This function adds cookie fields from stored cookies to
        the specified HTTP request.

        @note Undefined behavior if called twice on the same request object.
    */
    template<class Body, class Fields>
    void
    add(request<Body, Fields>& req);
};
```

This interface uses CRTP (Curiously Recurring Template Pattern) where the derived class provides behaviors like saving to disk or filtering values.

**Comment by octopus-prime** [comment]
> This interface uses CRTP
What is the base class?

**Comment by vinniefalco** [comment]
Someone who builds a client would call into this interface. Or if we're going low level then anyone who is writing client code in Beast would call into it for every request and response.

**Comment by vinniefalco** [comment]
This is outside the scope of Beast for now, closing

**Comment by kingofoz** [comment]
Looks it is not difficult to implement cookie-jar. Why not write an example for it at least?

**Comment by vinniefalco** [comment]
Okay, well then why don't you write it?

**Comment by kingofoz** [comment]
um..I am very new to beast and C++. I think I cannot write it with high quality and I still need much time to learn them.

**Comment by luz-arreola** [comment]
Hello Vinnie hope you're doing well.  I am obtaining the entire cookie header as follows:

std::string str = req[http::field::cookie].to_string();

I then parse the string myself since there does not seem to be a cookie parser in this library.  Is this a good approach or is there a built in parsing technique that I'm unaware of?  Thank you.
