### ISSUE TITLE
Mixing std::uint64_t and std::size_t

### ISSUE THREAD

**Issue by octopus-prime** [vinniefalco/Beast#539]
Because of #536 i had a deeper look to your body implementations.
There you mix `std::uint64_t` and `std::size_t`.
Is this purpose or mistake?

**Comment by vinniefalco** [comment]
It is on purpose. Beast supports HTTP messages whose Content-Length is up to 2^64-1 bytes, even when the address model used to build the application is 32-bit (i.e. when `std::size_t` is 32 bits). So I have been very careful to use `std::size_t` in places where it makes sense, such as when referring to the size of a dynamic allocation, and to use `std::uint64_t` when it refers to the size of something specified by the protocol such as the content length.

**Comment by octopus-prime** [comment]
okay -> close
