### ISSUE TITLE
code style templates `bool isRequest`

### ISSUE THREAD

**Issue by qwertzui11** [vinniefalco/Beast#542]
### Version of Beast
v67

### issue
throughout the library you use
`template<bool isRequest, [...]`
which results in
`beast::http::parser<true, [...]>`
wouldn't it be cleaner if it'd be
`template<enum Type, [...]`
with the result
`beast::http::parser<beast::http::type::request, [...]>`
https://blog.ometer.com/2011/01/20/boolean-parameters-are-wrong/
> Robert C. Martin's Clean Code Tip #12: Eliminate Boolean Arguments

**Comment by vinniefalco** [comment]
You want to add `enum type` to `beast::http::`?

**Comment by qwertzui11** [comment]
no. I'm suggesting, that using true/false for the message type may gets interpreted as "bad practice".

**Comment by vinniefalco** [comment]
Well you're not the first to complain :) I rather like `bool`. Its concise and expresses the dual nature of messages quite well. I have no desire to replace `bool`, `true`, and `false` with `beast::http::kind`, `beast::http::kind::request`, and `beast::http::kind::response'.

**Comment by qwertzui11** [comment]
check, asked and answered :smile:

**Comment by vinniefalco** [comment]
If you feel strongly about it, consider participating in the Boost formal review! Just sign up at the Boost developers mailing list. Any comments or criticisms are welcome. You can raise this point, but if you would offer a post with your experiences using the library (good or bad) that would be **extremely** helpful not only for the formal review process but also to help me make the library better at suiting everyone's needs. Sign up here:
http://www.boost.org/community/groups.html#main
