### ISSUE TITLE
Add basic_string_body

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/Beast#559]
We need `basic_string_body` to allow choices for `CharT`, `Traits`, and most importantly `Allocator` for tests.

**Comment by octopus-prime** [comment]
Hmm...
Now you want to start making `string_body` "configurable".
We have "configurable" `string_body`s called `const_body` and `mutable_body`.
They are more flexible and powerful than the `basic_string_body` which would be **tight bounded** to `std::basic_string`

**Comment by vinniefalco** [comment]
I'm also okay with not having it, even if it comes at the expense of a few lines of coverage

**Comment by octopus-prime** [comment]
Yes. I think so too.
If we decide to have configurable string_body we should do the big step and loosely bind to concepts.
This might be a future task. And may be the formal review will bring new insights.
So we should wait...

**Comment by vinniefalco** [comment]
This is superceded by https://github.com/vinniefalco/Beast/issues/580
