### ISSUE TITLE
handling of http code 422

### ISSUE THREAD

**Issue by jimhansson** [vinniefalco/Beast#592]
using version 66 of beast I get a bad_status when the server return http status 422, not sure what I really expect instead but something more would have been nice. The body of response may still be of value, but as I understand it is not possible to restart the parse, and get the rest of the information?.

**Comment by vinniefalco** [comment]
You are reading an HTTP response with a 422 status-code? You should get the whole message. Why do you think you aren't getting the whole message? How are you reading it?

**Comment by jimhansson** [comment]
I have modified the first example http://vinniefalco.github.io/beast/beast/quick_start.html#beast.quick_start.http_client so that if the check of `ec` after the `read` operation fails, I try to print the `res` to standard output. All i get is `HTTP/1.1 w65 <unknown-status>` while if the operation completes without bad_status i am able to print the whole body.

another question i have is how do i get the exact http status code?

**Comment by vinniefalco** [comment]
Hmmm, yes - it looks like the response is not a valid HTTP message. Beast doesn't try and "salvage" the parse operation. Nor should you, because that's a security risk.

>another question i have is how do i get the exact http status code?
Call `result_int()` http://vinniefalco.github.io/beast/beast/ref/beast__http__header/result_int.html

**Comment by vinniefalco** [comment]
Something like this might work (note: untested)
```
    // Read the response
    //http::read(sock, b, res, ec); // comment this out
    std::string s;
    s.resize(4096);
    s.resize(sock.read_some(boost::asio::const_buffer(buf.data(), buf.size()), ec));
    // At this point, look at the value of `s`
```

**Comment by jimhansson** [comment]
HTTP/1.1 422
Date: Tue, 04 Jul 2017 06:49:04 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d3a7f17d68e21ba854be2bf736c73ce261499150944; expires=Wed, 04-Jul-18 06:49:04 GMT; path=/; domain=.poloniex.com; HttpOnly
Cache-Control: private
Server: cloudflare-nginx
CF-RAY: 3790247bfaa70761-AMS

55
{"error":"Nonce must be greater than 999999999999999. You provided 999999999999999."}

**Comment by vinniefalco** [comment]
LOL polo :)

I don't think `HTTP/1.1 422\r\n` is a valid status-line, its missing the reason-phrase. Let me look at rfc7230.

**Comment by vinniefalco** [comment]
BNF (https://tools.ietf.org/html/rfc7230#section-3.1.2)
```
    status-line = HTTP-version SP status-code SP reason-phrase CRLF
    reason-phrase = *( HTAB / SP / VCHAR / obs-text )
```

There needs to be at least a space after the status-code, so it looks like that server is not producing a valid response.

**Comment by jimhansson** [comment]
yes, that seems to be the problem, I have another issue i am going to mail them about, so I might as well include that too. considering this closed now. thanks for the help

**Comment by vinniefalco** [comment]
I'm kind of concerned that an industry standard ("cloudflare-nginx") doesn't send back valid HTTP

**Comment by ndusart** [comment]
@vinniefalco is there a way to make the parser more lenient about this or do we have to go back to use asio socket directly ?

It can be blocking for interfacing with some non compliant servers and the status code is enough to determine the status of the response.

**Comment by vinniefalco** [comment]
In the current version there is no way to make the parser more lenient but a future version may explore this.
