### ISSUE TITLE
How to access the values of headers in HTTP reponse?

### ISSUE THREAD

**Issue by karengabrielyan** [vinniefalco/Beast#596]
Hi,

I could not figure out from documentation and code how one can access the values of the headers that come back with HTTP reponse.

Can you explain?

If I have the variable below, how can I access let's say the Location header that comes back as part of HTTP 302 redirect response?
      `beast::http::response<beast::http::dynamic_body> httpResponse;`

**Comment by vinniefalco** [comment]
These two statements are equivalent:
```
std::cout << "Location: " << httpResponse[beast::http::field::location] << std::endl;
std::cout << "Location: " << httpResponse["Location"] << std::endl;
```

Hope this helps!

**Comment by vinniefalco** [comment]
The `beast::http::message` inherits all of the members from the **Fields** it is derived from. So for `beast::http::response` (or `beast::http::request`) using the default fields type, you have all these members:
http://vinniefalco.github.io/beast/beast/ref/beast__http__basic_fields.html

Thanks

**Comment by karengabrielyan** [comment]
Thanks, works very well!

Might just be worth to add a new passage to the Usage section on this page explaining the headers access, to help with the Boost review.
http://vinniefalco.github.io/beast/beast/using_http/message_containers.html

Something in line with:

> Access headers and content of the Repsonse
> ...

Awesome library, thank you!

**Comment by vinniefalco** [comment]
Good idea!
