### ISSUE TITLE
convert buffer to string

### ISSUE THREAD

**Issue by WeissGotsman** [vinniefalco/Beast#617]
the beast version 72 does not contain beast::to_string, then which api should I use to convert from beast::multi_buffer to std::string

**Comment by vinniefalco** [comment]
`to_string` was provided as a way to display the contents of a buffer. For example:
```
multi_buffer b;
...
std:out << to_string(b.data());
```
The function sort of didn't belong in Beast because its expensive and there are other ways to accomplish the same result. For example, you can now write this instead:
```
std::out << buffers(b.data());
```

Alternatively you can use something other than a `multi_buffer`, such as a `flat_buffer`, and construct a `string_view` from it.

What is your use-case?

**Comment by WeissGotsman** [comment]
Ah, I just found the beast::buffers api right after my post. 

One one my use case is performance critical: streaming real-time big data up to 20Mbps from a several Websocket servers and then parse them for analysis. So fast memory operations are preferred

**Comment by vinniefalco** [comment]
Does your parser require a single contiguous input or can it work with sequence of multiple buffers?

**Comment by WeissGotsman** [comment]
it works with sequence of multiple buffers.

It's a series of json or quasi json data

**Comment by vinniefalco** [comment]
`multi_buffer` is good for you then. are there any bottlenecks in Beast? Are you using a profiler?

**Comment by WeissGotsman** [comment]
I'm using Beast in a "multi-threaded, async within each thread" fashion (both http and websocket clients), and so far I haven't noticed any bottleneck, the data streaming seems consistent. 

I do have done a http request per second performance comparison with wrk (https://github.com/wg/wrk), using http server crow (https://github.com/ipkn/crow) on a dual Xeon E5 2665 cpu machine, the performance is around half of wrk, roughly 25000 rps.

**Comment by vinniefalco** [comment]
Please let me know what I can do to help to make sure Beast does what you need!

**Comment by WeissGotsman** [comment]
Sure, and glad to to see beast is evolving actively.

**Comment by vinniefalco** [comment]
Just wondering, have you starred the repo?

**Comment by WeissGotsman** [comment]
I follow you instead.. ;)

vinnie, focus on your boost incubator, once admitted, it could bring you 10x stars!

**Comment by vinniefalco** [comment]
LMAO
