### ISSUE TITLE
pausation::emplace BOOST_ASSERT(! base_);

### ISSUE THREAD

**Issue by monada99** [vinniefalco/Beast#627]
Hello, Can I call ws.async_read and ws.async_write methods from different threads? Because I have error:

pausation.hpp:149
void beast::websocket::detail::pausation::emplace(F&&) [with F = beast::websocket::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp>&>::write_frame_op<beast::buffer_prefix_view<beast::consuming_buffers<boost::asio::const_buffers_1> >, beast::websocket::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp>&>::write_op<boost::asio::const_buffers_1, easynet::connection::send(const string&)::<lambda(const boost::system::error_code&)> > >]: Assertion `! base_' failed.

**Comment by vinniefalco** [comment]
You cannot call *any* members from different threads concurrently. You have to make all your calls from the same implicit or explicit strand. Beast websocket streams work just like Asio streams - they are not thread-safe (even though you are *using* threads in your `io_service`).

**Comment by monada99** [comment]
Thank you, but it  does not help me, I use one thread for my 'async_read' and 'async_write' operations now but I have error still.

pausation.hpp:149
void beast::websocket::detail::pausation::emplace(F&&) [with F = beast::websocket::streamboost::asio::basic_stream_socket<boost::asio::ip::tcp&>::write_frame_opbeast::buffer_prefix_view<beast::consuming_buffers<boost::asio::const_buffers_1 >, beast::websocket::streamboost::asio::basic_stream_socket<boost::asio::ip::tcp&>::write_op<boost::asio::const_buffers_1, easynet::connection::send(const string&)::<lambda(const boost::system::error_code&)> > >]: Assertion `! base_' failed.

What I can do? Thank you.

**Comment by vinniefalco** [comment]
The other reason that this assert comes up is if you try to call `async_read` or `async_write` twice without an intermediate completion. Is your code on GitHub where I can see it? Or can you post a gist?

**Comment by monada99** [comment]
Thank you very much, it help me. I call "async_write" several without an intermediate completion.

**Comment by vinniefalco** [comment]
Sounds like this is resolved, so I'll go ahead and close the issue. If you have another problem feel free to open a new issue any time, thanks!
