### ISSUE TITLE
Can't reuse http::response< http::string_body > 

### ISSUE THREAD

**Issue by ksergey** [vinniefalco/Beast#635]
Hello,

Looks like http::response body not cleared during executing http request. Is it expected behaviour? Is `http::response<...>` is reusable object?

Thanks

**Comment by vinniefalco** [comment]
Are you asking if `beast::http::write` clears the body after sending the message? No, it does not. The function accepts a `const&`, it cannot modify the message.

Why do you want to clear the message? Maybe its something I can add. If you want to reuse the variable you could put it in a `boost::optional` and just `emplace` it every time you want to use it.

**Comment by ksergey** [comment]
@vinniefalco thanks, boost::optional is solution for me
