### ISSUE TITLE
Websocket protocol violation

### ISSUE THREAD

**Issue by furchtlos** [vinniefalco/Beast#636]
Beast Version: 70
Compiler: MSVC v141, compiled into an x86 binary

Calling async_write returns the error `Websocket connection failed due to a protocol violation.` 

```
auto rtn = handle_read();

timer_.expires_from_now(std::chrono::seconds(15));

// Write Auth Message
ws_.async_write(boost::asio::buffer(&rtn[0], rtn.size()),
    strand_.wrap(std::bind(&connection::on_write,
        shared_from_this(), std::placeholders::_1)));
```

handle_read() is a function that returns a std::string based on the message read from the server. Sometimes a uint64_t that's been converted to an std::string, sometimes a hash. I've validated with a debugger that the string returned from handle_read is valid, printing and changing the string works fine as well as just turning it into a boost::asio::mutable_buffer, only when writing it does this occur.

**Comment by vinniefalco** [comment]
>Calling async_write returns the error Websocket connection failed due to a protocol violation.

That message corresponds to `websocket::error::failed` and can only be generated by a read operation:

https://github.com/vinniefalco/Beast/blob/fa1ac16584f03590ecea617a0dc2d8c86e48cda5/include/beast/websocket/impl/read.ipp#L663

https://github.com/vinniefalco/Beast/blob/fa1ac16584f03590ecea617a0dc2d8c86e48cda5/include/beast/websocket/impl/read.ipp#L677

I don't see how its possible for `async_write` to return that error. Here are all the places where `async_write` raises a specific error code:

https://github.com/vinniefalco/Beast/blob/fa1ac16584f03590ecea617a0dc2d8c86e48cda5/include/beast/websocket/impl/write.ipp#L485

It looks like you're running under Visual Studio, could you set a breakpoint on all occurrences of `ec = error::failed;` and get more information? That would help to track this down

Thanks

**Comment by furchtlos** [comment]
Sorry I made a bit of confusion. The error is thrown on a read operation, I just meant that using that write call is what is causing the error. Echoing back the sent binary works fine.

https://pastebin.com/QkXWhNYt This is the values for ec, and the error is being thrown in read.ipp, line 976.

**Comment by vinniefalco** [comment]
You are using Beast for both client and server?

**Comment by vinniefalco** [comment]
>read.ipp, line 976.

This means that the other end is closing the websocket connection with a particular close code. Are you in control of the other end? The reason you are getting `error::failed` is because they did not cleanly shut down the connection.

**Comment by furchtlos** [comment]
I am using Beast for both client and Server. Let me log my server for a second and I'll step through and see where the close is sent.

**Comment by vinniefalco** [comment]
The "Close the websocket connection" path (which causes the close frame to be sent) can be triggered from these locations:

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L216

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L247

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L324

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L365

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L387

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L480

The actual close frame is sent from here:

https://github.com/vinniefalco/Beast/blob/78a065ba39836d91d7e70d93de7f9140f518083b/include/beast/websocket/impl/read.ipp#L645

Thanks

**Comment by furchtlos** [comment]
So stepping through the code, here's essentially what happens now. The client opens a connection, handshakes properly, and writes the username to the server. The server reads correctly, handles the data and sends back a randomly generated number to use as an auth seed. Before the client receives the random number and after the server has sent it, the last call to be made is an async_read on the server's end. After this, the breakpoint on error::failed is triggered.

I set a breakpoint on every line you provided and it didn't trigger on any of them. At this point, I'll be happy to show you my source if you would like to inspect what's wrong, or I can also upgrade to the latest version of beast.

**Comment by vinniefalco** [comment]
I'll have a look, my email is vinnie.falco@gmail.com if you would like to keep the communications private (anything you send by email is presumed confidential unless otherwise specified).

**Comment by vinniefalco** [comment]
Version 70 was June 28th, I don't see anything since then that might fix a bug in websocket:
https://github.com/vinniefalco/Beast/commits/develop/include/beast/websocket

That's the theory anyway. In practice who knows :) This is a mystery.

**Comment by vinniefalco** [comment]
I responded by email, have we discovered the problem?

**Comment by furchtlos** [comment]
I don't feel like opening another issue but to continue this on, but the protocol violation was caused by writing a string of random numbers with the binary type of text. Using `ws_.binary(true);` solved the issue of the protocol error, however the data recieved on the client would be completely corrupted and be an array of null characters.

Ex: 
```Sent: "7459114088365490217"
Received: "ÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝ"```

**Comment by vinniefalco** [comment]
Is this resolved?

**Comment by vinniefalco** [comment]
Feel free to open a new issue if you get stuck again!

**Comment by tigerpeng** [comment]
i have got the shame errors
