### ISSUE TITLE
Copy constructor/operator

### ISSUE THREAD

**Issue by ksergey** [vinniefalco/Beast#646]
file_posix, file_stdio, file_win32 is copyable. 
I think it's wrong behaviour

**Comment by vinniefalco** [comment]
eww..if that's true then its a bug!

**Comment by vinniefalco** [comment]
Are you sure its copy constructible? This assert does not fire:
```
BOOST_STATIC_ASSERT(! std::is_copy_constructible<file_win32>::value);
```

**Comment by ksergey** [comment]
@vinniefalco 
TIL 
> The implicitly-declared copy constructor for class T is undefined if any of the following conditions are true:	
>T has a user-defined move constructor or move assignment operator;

Sorry for that

**Comment by vinniefalco** [comment]
No problem, I had to double check it myself - I have added tests now so I think this was helpful!
