### ISSUE TITLE
Question regarding detect_ssl_op

### ISSUE THREAD

**Issue by akoolenbourke** [vinniefalco/Beast#648]
Hi there.

I was looking through the detect_ssl composed operation and noticed this line in the operator()

`return stream_.get_io_service().post(
   bind_handler(std::move(*this), ec, 0));
`
I realise (As stated in the comments) that this needs to happen because handlers can't be called before the initiating function returns. However, it is possible that immediately after the post(), a context switch happens, "pausing" the return operation and a new io.run() worker thread picks up the post and processes it.

I realise that in most (all?) situations this would likely have no real effect but does this violate the guarantee and is it of any concern?

Thanks

**Comment by vinniefalco** [comment]
Great question!! Yes that can happen, and it **will** happen, which means you need either an implicit or explicit strand:

* Implicit strand: only one thread calling `io_service::run`

* Explicit strand: good ole' `io_service::strand`

`beast::bind_handler` preserves the invocation hooks and forwards them to the underlying handler, so if `*this` invokes using a strand, then `bind_handler(std::move(*this), ...)` will also invoke using the same strand.

**Comment by akoolenbourke** [comment]
Thanks Vinnie. 

So, this does raise the question of performance.

I am currently going through an experimental phase to see how ASIO/Beast might work for us (We have a big network product and are looking to re-architect our IO) and it seems that the canonical way to build a pipeline of processing stages would be with composed operations. 

A thought experiment would have me developing a simple HTTP Tunnel (Via CONNECT). Using async_detect_ssl as an example I could have an async_detect_connect and the invocation of that might complete immediately if I  found a CONNECT verb in the buffer already. I would then call it's handler which might be an async_tunnel_data to start moving data from one socket to the next. This tunnel handler (Composed operation) would also need to be in a strand correct, because it was potentially invoked immediately in async_detect_connect. Thereby pushing the strand down the chain.

Am I thinking about this the right way or have I left planet earth?

Thanks and great work on Beast BTW.

**Comment by vinniefalco** [comment]
>it seems that the canonical way to build a pipeline of processing stages would be with composed operations.

This is the best in terms of performance but I'll warn you up front, writing composed operations requires particular skill acquired through trial and error. I've tried to polish those rough edges off as much as I could, with the tutorial in the documentation and also the set of helpers for composed operations.

You don't need to write a composed operation to get the CONNECT string, you can write this instead:
```
flat_buffer b;
request<empty_body> req;
read_header(sock, b, req);
if(req.method() == verb::connect)
    do_tunnel(sock);
// something else
```

The code above uses the synchronous interface but you can do the same thing using asynchronous calls.  

Where you **do** want a composed operation is your implementation of the relay function performed by your tunnel. Read from the downstream connection, write to the upstream connection, and vice versa. Probably best to implement that with one operation taking two sockets and then launch it twice (the second time with the order of sockets reversed).

When you write the composed operation you dont have to worry about the strand at all, you just have to follow the rules for composed operations:

* Don't type-erase the handler
* Forward the hooks (allocate, deallocate, invoke, is_continuation)
* Use the composed operation as the completion handler for intermediate operations (e.g. `std::move(*this)`)
* Manage complex state using `beast::handler_ptr`, simple state using a trivially copyable/movable composed operation.

You only see or worry about the strand at the highest level when you make your call to the initiating function, for example:
```
async_tunnel_some(from, to, strand_.wrap(
    std::bind(&connection::on_header, shared_from_this(), std::placeholders::_1)));
```

As long as your initiating function and associated composed operation follows the rules, everything will Just Work

**Comment by akoolenbourke** [comment]
Thanks

Sorry if I wasn't clear; the use of the strand at the highest level is the actual concern I have (re performance). Initiating with a strand implies that all of the operations within the composed operation will use that strand automatically because the handlers for intermediate calls will use something like std::move(*this). Now I realise that typically the operations in a composed operation are performed one after the other in a state machine and therefore handler concurrency is non existent, but is there any significant overhead to the fact that the handler needs to now go in a queue for the strand?

Also, I'm starting to wonder if we're talking at crossed purposes a little.

I understand the need for strands when you're firing off two simultaneous async operations and need to access shared state in the handlers. My issue is due to the race condition that seems to occur between the post() in immediately returning composed operations and the high level caller. e.g.

```
void guy::somefunc()
{
    async_do_something(socket, [this](error_code ec) // async_do_something completes immediately and posts
    {
       member_ = 42;  // This could be executed before async_do_other is called
    });
  
    async_do_other(second_socket,[this](error_code ec)
    {
        // code here never touches member_
    });

  // bunch of other code that never touches member_
    someothermember_ = 0;
}

```

In the above code, would I even need to bother with a strand in the initiating function in the first place, even though it might return AFTER the handler is called. i.e. Is the only real requirement that you don't call handlers from within initiating functions.

Is that clear as mud now?

Cheers

**Comment by vinniefalco** [comment]
I think you're worrying too much about a hypothetical race condition that doesn't exist. If a composed operation already on the strand posts to the same strand, the posted operation is appended to the queue associated with the strand and executed when the calling function returns, see:

https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/impl/strand_service.ipp#L40

**Comment by akoolenbourke** [comment]
Yeah I realise how the stranding works I just don't want to strand things I don't need to (there's locks in there etc). In the example I provided, I just wanted to clarify whether I needed to strand when a CO posts() immediately even though outside I'm not going to access shared resources.

**Comment by vinniefalco** [comment]
> I just wanted to clarify whether I needed to strand when a CO posts() immediately even though outside

How would the initiating function know if the composed operation will complete immediately? If it knew that, it could skip the initiating function and just do the operation.

@chriskohlhoff do you have anything you can add to this?

**Comment by akoolenbourke** [comment]
The way I was interpreting your comments is that I should ALWAYS use strand.wrap when calling an initiating function if the composed operation might return immediately (Would need to be documented per composed operation). And this was to avoid the race condition I raised in the initial post; that the post()ed handler gets called before the initiating function returns,.

However, is that even a concern? If, after calling the composed_op{}(), all the initiation function is doing is init.result.get() and returning to the initiating function that returns immediately to client code, does that matter if the handler was called before the init.result.get()? If not I would assume a strand is not necessary UNLESS you want to make another async operation from client code that has a handler that might access shared state and don't want it executing at the same time as the initial one.

**Comment by vinniefalco** [comment]
I'm not saying to always use `strand.wrap()`. I am saying that you must ensure that one of the following conditions is true:

* Every completion handler is protected by an *implicit strand*: only one thread calling `io_service::run`, OR

* Every completion handler is protected by an *explicit strand* (`io_service::strand`), OR

* Every completion handler uses a custom invocation hook provided by the caller to ensure that only safe accesses are made to the underlying stream or socket object (such objects are *not* thread safe; they may not be accessed concurrently from multiple threads).

> if the composed operation might return immediately

You are saying "might" which is the same as saying that the composed operation may call an intermediate initiating function. In this case, the strand is necessary.

If instead you mean "the composed operation always returns immediately" (as in, the composed operation always calls `post` with an immediate result instead of calling another initiating function) then what you have is not a composed operation at all but rather a function that performs some work and incurs the unnecessary expense of dispatching its result. I don't suppose you mean this one because it doesn't make sense.

As I said before, I think you're overthinking this. Write the composed operation as per best practices, and then at call sites use the strand if more than one thread is calling `io_service::run`.

**Comment by vinniefalco** [comment]
Perhaps you can demonstrate by posting sample code for a composed operation? Here's a simple one:
```



template <typename AsyncReadStream, typename Elem,
  | typename CompletionCondition, typename ReadHandler>
  | class read_op<AsyncReadStream, boost::array<Elem, 2>,
  | CompletionCondition, ReadHandler>
  | : detail::base_from_completion_cond<CompletionCondition>
  | {
  | public:
  | read_op(AsyncReadStream& stream, const boost::array<Elem, 2>& buffers,
  | CompletionCondition completion_condition, ReadHandler& handler)
  | : detail::base_from_completion_cond<
  | CompletionCondition>(completion_condition),
  | stream_(stream),
  | buffers_(buffers),
  | start_(0),
  | total_transferred_(0),
  | handler_(BOOST_ASIO_MOVE_CAST(ReadHandler)(handler))
  | {
  | }
  |  
  | #if defined(BOOST_ASIO_HAS_MOVE)
  | read_op(const read_op& other)
  | : detail::base_from_completion_cond<CompletionCondition>(other),
  | stream_(other.stream_),
  | buffers_(other.buffers_),
  | start_(other.start_),
  | total_transferred_(other.total_transferred_),
  | handler_(other.handler_)
  | {
  | }
  |  
  | read_op(read_op&& other)
  | : detail::base_from_completion_cond<CompletionCondition>(other),
  | stream_(other.stream_),
  | buffers_(other.buffers_),
  | start_(other.start_),
  | total_transferred_(other.total_transferred_),
  | handler_(BOOST_ASIO_MOVE_CAST(ReadHandler)(other.handler_))
  | {
  | }
  | #endif // defined(BOOST_ASIO_HAS_MOVE)
  |  
  | void operator()(const boost::system::error_code& ec,
  | std::size_t bytes_transferred, int start = 0)
  | {
  | typename boost::asio::detail::dependent_type<Elem,
  | boost::array<boost::asio::mutable_buffer, 2> >::type bufs = {{
  | boost::asio::mutable_buffer(buffers_[0]),
  | boost::asio::mutable_buffer(buffers_[1]) }};
  | std::size_t buffer_size0 = boost::asio::buffer_size(bufs[0]);
  | std::size_t buffer_size1 = boost::asio::buffer_size(bufs[1]);
  | std::size_t n = 0;
  | switch (start_ = start)
  | {
  | case 1:
  | n = this->check_for_completion(ec, total_transferred_);
  | for (;;)
  | {
  | bufs[0] = boost::asio::buffer(bufs[0] + total_transferred_, n);
  | bufs[1] = boost::asio::buffer(
  | bufs[1] + (total_transferred_ < buffer_size0
  | ? 0 : total_transferred_ - buffer_size0),
  | n - boost::asio::buffer_size(bufs[0]));
  | stream_.async_read_some(bufs, BOOST_ASIO_MOVE_CAST(read_op)(*this));
  | return; default:
  | total_transferred_ += bytes_transferred;
  | if ((!ec && bytes_transferred == 0)
  | || (n = this->check_for_completion(ec, total_transferred_)) == 0
  | || total_transferred_ == buffer_size0 + buffer_size1)
  | break;
  | }
  |  
  | handler_(ec, static_cast<const std::size_t&>(total_transferred_));
  | }
  | }
  |  
  | //private:
  | AsyncReadStream& stream_;
  | boost::array<Elem, 2> buffers_;
  | int start_;
  | std::size_t total_transferred_;
  | ReadHandler handler_;
  | };
 

```

**Comment by akoolenbourke** [comment]
Thanks Vinnie. Sorry for taking up so much of your time. I think we might need to move on for now as I'm obviously not understanding something deeper about handler invocation (I understand strands in their day to day usage) or not explaining myself clearly enough.

Your last condition (two posts above) does clarify some things I *think* as I am taking from that that so long as the completion handler (Even if it's just a lambda, nothing fancier) does not screw with anything that the client code might be doing asynchronously then I'm OK. 

If I get around to creating a composed operation I'll return here and post it so hopefully that would make it clearer. It would be nice to get to the bottom of it as it will affect how I approach the whole thing. 

Thanks

**Comment by vinniefalco** [comment]
Well if you are using `ssl::stream` you still need the strand if you launch any asynchronous operations

**Comment by vinniefalco** [comment]
It looks like there's nothing actionable for me here so I'll go ahead and close the issue to keep things tidy, feel free to open a new one at any time!
