### ISSUE TITLE
Deferred Body Type Example inconsistencies

### ISSUE THREAD

**Issue by eliottparis** [vinniefalco/beast#675]
In the [example_http_defer_body](https://github.com/vinniefalco/beast/blob/develop/example/doc/http_examples.hpp#L776), it say:

> Handle a form PUT request, choosing a body type depending on the Content-Type [...].

Shouldn't it be replaced by : *Handle a form **POST** request, [...]*, as the Content-Type is only checked on `http::verb::post` case [here](https://github.com/vinniefalco/beast/blob/develop/example/doc/http_examples.hpp#L820) ? 

I also think that the `do_string_body` `goto` statement [here](https://github.com/vinniefalco/beast/blob/develop/example/doc/http_examples.hpp#L825) should be renamed as `do_dynamic_body`.

**Comment by vinniefalco** [comment]
Yep, I agree with all of that, thanks! Do you want to submit a pull request or should I just do it?
