### ISSUE TITLE
Make the websocket handshake request customizable

### ISSUE THREAD

**Issue by z4kn4fein** [vinniefalco/Beast#70]
Currently the websocket handshake request is built up by the lib under the hood, but i need to decorate it with additional header values, please extend the interface with a handshake method which allows the request customization.

**Comment by vinniefalco** [comment]
How about this:
```
class set_subprotocols
{
    std::string s_;

public:
    explicit
    set_subprotocols(std::string s)
        : s_(s) {}

    template<bool isRequest, class Body, class Headers>
    void
    operator()(beast::http::message<isRequest, Body, Headers>& m)
    {
        m.headers.replace("Sec-WebSocket-Protocol", s_);
    }
};

using namespace beast::websocket;

stream<boost::ip::tcp::socket> ws;
...
ws.set_option(decorate(set_subprotocols{"mqtt"}));
```

I believe this works in the current version, see:
http://vinniefalco.github.io/beast/beast/ref/websocket__decorate.html

**Comment by z4kn4fein** [comment]
Thx, your solution is working properly, i'm going to close this issue.

**Comment by vinniefalco** [comment]
Glad to hear it!
