### ISSUE TITLE
BuildRequest not using resource parameter

### ISSUE THREAD

**Issue by PortableNuke** [vinniefalco/Beast#78]
I'm just getting started with websocket programming and thought that the Beast library would be a good place to started. I've been trying to put together a simple app that communicates with a websockets server and I noticed that the handshake is always issued as GET / rather than, for example, GET /myserver/serverpoint.

I notice that although you are expected to provide a resource during the handshake call this parameter, which is passed into the build_request function, is ignored and the url is explicitly set to "/". This looks like an oversight - shouldn't the resource be used in the construction of the req.url?

PortableNuke.

**Comment by vinniefalco** [comment]
@PortableNuke You are correct, and this issue has been fixed in *1.0.0-b11* as of August 26th:
https://github.com/vinniefalco/Beast/commit/878c0f2a19887114ca30c2ae4d298b8008985d5b

Current version is *1.0.0-b13* you should upgrade :-)

Thanks for the heads up!

**Comment by PortableNuke** [comment]
Okay, that's good to know. I'll make sure to upgrade to the latest version.

Thanks,

PortableNuke
