### ISSUE TITLE
CMake install target

### ISSUE THREAD

**Issue by e-fominov** [vinniefalco/Beast#93]
Beast now has no "installation" target in CMakeFiles.txt. If I run `cmake --build . --target install` - i get an error. 
Even if Beast is header-only, it will be good to make it available to other projects so they will be able to use `find_package(Beast)`
I know how to make it. If you agree - I will make PR

**Comment by vinniefalco** [comment]
What happens when Beast becomes part of Boost?

**Comment by e-fominov** [comment]
When it happen, users will use `find_package(Boost)'. You can look at Boost's hana library - it has [CMakeFiles.txt](https://github.com/boostorg/hana/blob/master/CMakeLists.txt#L176)

**Comment by vinniefalco** [comment]
I guess it can't hurt then

**Comment by vinniefalco** [comment]
This is not something that I can support, sorry.
